//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markum.Cloud.Libraries.Service1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service1.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemOption", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSystemOption(string query, int scope, string valueName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemOption", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSystemOptionAsync(string query, int scope, string valueName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POPRetrieval", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int POPRetrieval(string postoffice, string mailbox, string mailserver, long port, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POPRetrieval", ReplyAction="*")]
        System.Threading.Tasks.Task<int> POPRetrievalAsync(string postoffice, string mailbox, string mailserver, long port, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListMailbox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Service1.ListMailboxResponse ListMailbox(Markum.Cloud.Libraries.Service1.ListMailboxRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListMailbox", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.ListMailboxResponse> ListMailboxAsync(Markum.Cloud.Libraries.Service1.ListMailboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long RemoveLogin(string PostOffice, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<long> RemoveLoginAsync(string PostOffice, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPostoffice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Service1.ListPostofficeResponse ListPostoffice(Markum.Cloud.Libraries.Service1.ListPostofficeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPostoffice", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.ListPostofficeResponse> ListPostofficeAsync(Markum.Cloud.Libraries.Service1.ListPostofficeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPOPRetriever", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long GetPOPRetriever(string postoffice, string mailserver, long port, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPOPRetriever", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetPOPRetrieverAsync(string postoffice, string mailserver, long port, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWindowsServiceStatusID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        int GetWindowsServiceStatusID(string MailEnableServiceTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWindowsServiceStatusID", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetWindowsServiceStatusIDAsync(string MailEnableServiceTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWindowsServiceStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        System.Data.DataTable GetWindowsServiceStatus(System.Data.DataTable MailEnableWinService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWindowsServiceStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetWindowsServiceStatusAsync(System.Data.DataTable MailEnableWinService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        void StartService(string MailEnableServiceTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartService", ReplyAction="*")]
        System.Threading.Tasks.Task StartServiceAsync(string MailEnableServiceTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StopService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        void StopService(string MailEnableServiceTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StopService", ReplyAction="*")]
        System.Threading.Tasks.Task StopServiceAsync(string MailEnableServiceTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RestartService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        void RestartService(string MailEnableServiceTypeName, int timeoutMilliseconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RestartService", ReplyAction="*")]
        System.Threading.Tasks.Task RestartServiceAsync(string MailEnableServiceTypeName, int timeoutMilliseconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BackupConfig", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        void BackupConfig(string type, string configpath, string backuppath, int maxbackup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BackupConfig", ReplyAction="*")]
        System.Threading.Tasks.Task BackupConfigAsync(string type, string configpath, string backuppath, int maxbackup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDisks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Service1.DiskInfo[] GetDisks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDisks", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.DiskInfo[]> GetDisksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageCommands", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Service1.MessageCommand[] GetMessageCommands(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageCommands", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.MessageCommand[]> GetMessageCommandsAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMessageCommandFiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        void DeleteMessageCommandFiles(string path, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMessageCommandFiles", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteMessageCommandFilesAsync(string path, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMessageCommandFilesByRecipient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        void DeleteMessageCommandFilesByRecipient(string path, string recipient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMessageCommandFilesByRecipient", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteMessageCommandFilesByRecipientAsync(string path, string recipient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMessageCommandFilesByClientIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        void DeleteMessageCommandFilesByClientIP(string path, string clientip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMessageCommandFilesByClientIP", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteMessageCommandFilesByClientIPAsync(string path, string clientip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageCommandsBySender", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Service1.MessageCommand[] GetMessageCommandsBySender(string path, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageCommandsBySender", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.MessageCommand[]> GetMessageCommandsBySenderAsync(string path, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageCommandsByRecipient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Service1.MessageCommand[] GetMessageCommandsByRecipient(string path, string recipient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageCommandsByRecipient", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.MessageCommand[]> GetMessageCommandsByRecipientAsync(string path, string recipient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageCommandsByClientIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Service1.MessageCommand[] GetMessageCommandsByClientIP(string path, string clientip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageCommandsByClientIP", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.MessageCommand[]> GetMessageCommandsByClientIPAsync(string path, string clientip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadMessageCommandFileText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        string ReadMessageCommandFileText(string path, string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadMessageCommandFileText", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReadMessageCommandFileTextAsync(string path, string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadMessageFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        string ReadMessageFile(string path, string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadMessageFile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReadMessageFileAsync(string path, string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestMe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        string TestMe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestMe", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TestMeAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Mailbox : MarshalByRefObject {
        
        private string postofficeField;
        
        private string mailboxNameField;
        
        private string redirectAddressField;
        
        private long redirectStatusField;
        
        private long statusField;
        
        private long limitField;
        
        private long sizeField;
        
        private string hostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Postoffice {
            get {
                return this.postofficeField;
            }
            set {
                this.postofficeField = value;
                this.RaisePropertyChanged("Postoffice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MailboxName {
            get {
                return this.mailboxNameField;
            }
            set {
                this.mailboxNameField = value;
                this.RaisePropertyChanged("MailboxName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RedirectAddress {
            get {
                return this.redirectAddressField;
            }
            set {
                this.redirectAddressField = value;
                this.RaisePropertyChanged("RedirectAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long RedirectStatus {
            get {
                return this.redirectStatusField;
            }
            set {
                this.redirectStatusField = value;
                this.RaisePropertyChanged("RedirectStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("Limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
                this.RaisePropertyChanged("Host");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Postoffice))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Mailbox))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageCommand : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIDField;
        
        private string senderField;
        
        private string[] recipientsField;
        
        private string accountField;
        
        private string statusField;
        
        private string clientIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] Recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
                this.RaisePropertyChanged("Recipients");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("Account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ClientIP {
            get {
                return this.clientIPField;
            }
            set {
                this.clientIPField = value;
                this.RaisePropertyChanged("ClientIP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DiskInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long totalSizeField;
        
        private long totalFreeSpaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long TotalSize {
            get {
                return this.totalSizeField;
            }
            set {
                this.totalSizeField = value;
                this.RaisePropertyChanged("TotalSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long TotalFreeSpace {
            get {
                return this.totalFreeSpaceField;
            }
            set {
                this.totalFreeSpaceField = value;
                this.RaisePropertyChanged("TotalFreeSpace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Postoffice : MarshalByRefObject {
        
        private string nameField;
        
        private long statusField;
        
        private string accountField;
        
        private string hostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("Account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
                this.RaisePropertyChanged("Host");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListMailbox", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListMailboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Markum.Cloud.Libraries.Service1.Mailbox[] ObjectList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Postoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public long Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public long Size;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public long Top;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public long MaxLength;
        
        public ListMailboxRequest() {
        }
        
        public ListMailboxRequest(Markum.Cloud.Libraries.Service1.Mailbox[] ObjectList, string Postoffice, long Status, long Size, long Top, long MaxLength) {
            this.ObjectList = ObjectList;
            this.Postoffice = Postoffice;
            this.Status = Status;
            this.Size = Size;
            this.Top = Top;
            this.MaxLength = MaxLength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListMailboxResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListMailboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long ListMailboxResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Markum.Cloud.Libraries.Service1.Mailbox[] ObjectList;
        
        public ListMailboxResponse() {
        }
        
        public ListMailboxResponse(long ListMailboxResult, Markum.Cloud.Libraries.Service1.Mailbox[] ObjectList) {
            this.ListMailboxResult = ListMailboxResult;
            this.ObjectList = ObjectList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPostoffice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListPostofficeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Markum.Cloud.Libraries.Service1.Postoffice[] ObjectList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Postoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public long Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int Page;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int Paging;
        
        public ListPostofficeRequest() {
        }
        
        public ListPostofficeRequest(Markum.Cloud.Libraries.Service1.Postoffice[] ObjectList, string Postoffice, long Status, int Page, int Paging) {
            this.ObjectList = ObjectList;
            this.Postoffice = Postoffice;
            this.Status = Status;
            this.Page = Page;
            this.Paging = Paging;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPostofficeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListPostofficeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long ListPostofficeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Markum.Cloud.Libraries.Service1.Postoffice[] ObjectList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int TotalCount;
        
        public ListPostofficeResponse() {
        }
        
        public ListPostofficeResponse(long ListPostofficeResult, Markum.Cloud.Libraries.Service1.Postoffice[] ObjectList, int TotalCount) {
            this.ListPostofficeResult = ListPostofficeResult;
            this.ObjectList = ObjectList;
            this.TotalCount = TotalCount;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Markum.Cloud.Libraries.Service1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Markum.Cloud.Libraries.Service1.Service1Soap>, Markum.Cloud.Libraries.Service1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSystemOption(string query, int scope, string valueName) {
            return base.Channel.GetSystemOption(query, scope, valueName);
        }
        
        public System.Threading.Tasks.Task<string> GetSystemOptionAsync(string query, int scope, string valueName) {
            return base.Channel.GetSystemOptionAsync(query, scope, valueName);
        }
        
        public int POPRetrieval(string postoffice, string mailbox, string mailserver, long port, string username, string password) {
            return base.Channel.POPRetrieval(postoffice, mailbox, mailserver, port, username, password);
        }
        
        public System.Threading.Tasks.Task<int> POPRetrievalAsync(string postoffice, string mailbox, string mailserver, long port, string username, string password) {
            return base.Channel.POPRetrievalAsync(postoffice, mailbox, mailserver, port, username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Service1.ListMailboxResponse Markum.Cloud.Libraries.Service1.Service1Soap.ListMailbox(Markum.Cloud.Libraries.Service1.ListMailboxRequest request) {
            return base.Channel.ListMailbox(request);
        }
        
        public long ListMailbox(ref Markum.Cloud.Libraries.Service1.Mailbox[] ObjectList, string Postoffice, long Status, long Size, long Top, long MaxLength) {
            Markum.Cloud.Libraries.Service1.ListMailboxRequest inValue = new Markum.Cloud.Libraries.Service1.ListMailboxRequest();
            inValue.ObjectList = ObjectList;
            inValue.Postoffice = Postoffice;
            inValue.Status = Status;
            inValue.Size = Size;
            inValue.Top = Top;
            inValue.MaxLength = MaxLength;
            Markum.Cloud.Libraries.Service1.ListMailboxResponse retVal = ((Markum.Cloud.Libraries.Service1.Service1Soap)(this)).ListMailbox(inValue);
            ObjectList = retVal.ObjectList;
            return retVal.ListMailboxResult;
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.ListMailboxResponse> ListMailboxAsync(Markum.Cloud.Libraries.Service1.ListMailboxRequest request) {
            return base.Channel.ListMailboxAsync(request);
        }
        
        public long RemoveLogin(string PostOffice, string Username) {
            return base.Channel.RemoveLogin(PostOffice, Username);
        }
        
        public System.Threading.Tasks.Task<long> RemoveLoginAsync(string PostOffice, string Username) {
            return base.Channel.RemoveLoginAsync(PostOffice, Username);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Service1.ListPostofficeResponse Markum.Cloud.Libraries.Service1.Service1Soap.ListPostoffice(Markum.Cloud.Libraries.Service1.ListPostofficeRequest request) {
            return base.Channel.ListPostoffice(request);
        }
        
        public long ListPostoffice(ref Markum.Cloud.Libraries.Service1.Postoffice[] ObjectList, string Postoffice, long Status, int Page, int Paging, out int TotalCount) {
            Markum.Cloud.Libraries.Service1.ListPostofficeRequest inValue = new Markum.Cloud.Libraries.Service1.ListPostofficeRequest();
            inValue.ObjectList = ObjectList;
            inValue.Postoffice = Postoffice;
            inValue.Status = Status;
            inValue.Page = Page;
            inValue.Paging = Paging;
            Markum.Cloud.Libraries.Service1.ListPostofficeResponse retVal = ((Markum.Cloud.Libraries.Service1.Service1Soap)(this)).ListPostoffice(inValue);
            ObjectList = retVal.ObjectList;
            TotalCount = retVal.TotalCount;
            return retVal.ListPostofficeResult;
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.ListPostofficeResponse> ListPostofficeAsync(Markum.Cloud.Libraries.Service1.ListPostofficeRequest request) {
            return base.Channel.ListPostofficeAsync(request);
        }
        
        public long GetPOPRetriever(string postoffice, string mailserver, long port, string username) {
            return base.Channel.GetPOPRetriever(postoffice, mailserver, port, username);
        }
        
        public System.Threading.Tasks.Task<long> GetPOPRetrieverAsync(string postoffice, string mailserver, long port, string username) {
            return base.Channel.GetPOPRetrieverAsync(postoffice, mailserver, port, username);
        }
        
        public int GetWindowsServiceStatusID(string MailEnableServiceTypeName) {
            return base.Channel.GetWindowsServiceStatusID(MailEnableServiceTypeName);
        }
        
        public System.Threading.Tasks.Task<int> GetWindowsServiceStatusIDAsync(string MailEnableServiceTypeName) {
            return base.Channel.GetWindowsServiceStatusIDAsync(MailEnableServiceTypeName);
        }
        
        public System.Data.DataTable GetWindowsServiceStatus(System.Data.DataTable MailEnableWinService) {
            return base.Channel.GetWindowsServiceStatus(MailEnableWinService);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetWindowsServiceStatusAsync(System.Data.DataTable MailEnableWinService) {
            return base.Channel.GetWindowsServiceStatusAsync(MailEnableWinService);
        }
        
        public void StartService(string MailEnableServiceTypeName) {
            base.Channel.StartService(MailEnableServiceTypeName);
        }
        
        public System.Threading.Tasks.Task StartServiceAsync(string MailEnableServiceTypeName) {
            return base.Channel.StartServiceAsync(MailEnableServiceTypeName);
        }
        
        public void StopService(string MailEnableServiceTypeName) {
            base.Channel.StopService(MailEnableServiceTypeName);
        }
        
        public System.Threading.Tasks.Task StopServiceAsync(string MailEnableServiceTypeName) {
            return base.Channel.StopServiceAsync(MailEnableServiceTypeName);
        }
        
        public void RestartService(string MailEnableServiceTypeName, int timeoutMilliseconds) {
            base.Channel.RestartService(MailEnableServiceTypeName, timeoutMilliseconds);
        }
        
        public System.Threading.Tasks.Task RestartServiceAsync(string MailEnableServiceTypeName, int timeoutMilliseconds) {
            return base.Channel.RestartServiceAsync(MailEnableServiceTypeName, timeoutMilliseconds);
        }
        
        public void BackupConfig(string type, string configpath, string backuppath, int maxbackup) {
            base.Channel.BackupConfig(type, configpath, backuppath, maxbackup);
        }
        
        public System.Threading.Tasks.Task BackupConfigAsync(string type, string configpath, string backuppath, int maxbackup) {
            return base.Channel.BackupConfigAsync(type, configpath, backuppath, maxbackup);
        }
        
        public Markum.Cloud.Libraries.Service1.DiskInfo[] GetDisks() {
            return base.Channel.GetDisks();
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.DiskInfo[]> GetDisksAsync() {
            return base.Channel.GetDisksAsync();
        }
        
        public Markum.Cloud.Libraries.Service1.MessageCommand[] GetMessageCommands(string path) {
            return base.Channel.GetMessageCommands(path);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.MessageCommand[]> GetMessageCommandsAsync(string path) {
            return base.Channel.GetMessageCommandsAsync(path);
        }
        
        public void DeleteMessageCommandFiles(string path, string sender) {
            base.Channel.DeleteMessageCommandFiles(path, sender);
        }
        
        public System.Threading.Tasks.Task DeleteMessageCommandFilesAsync(string path, string sender) {
            return base.Channel.DeleteMessageCommandFilesAsync(path, sender);
        }
        
        public void DeleteMessageCommandFilesByRecipient(string path, string recipient) {
            base.Channel.DeleteMessageCommandFilesByRecipient(path, recipient);
        }
        
        public System.Threading.Tasks.Task DeleteMessageCommandFilesByRecipientAsync(string path, string recipient) {
            return base.Channel.DeleteMessageCommandFilesByRecipientAsync(path, recipient);
        }
        
        public void DeleteMessageCommandFilesByClientIP(string path, string clientip) {
            base.Channel.DeleteMessageCommandFilesByClientIP(path, clientip);
        }
        
        public System.Threading.Tasks.Task DeleteMessageCommandFilesByClientIPAsync(string path, string clientip) {
            return base.Channel.DeleteMessageCommandFilesByClientIPAsync(path, clientip);
        }
        
        public Markum.Cloud.Libraries.Service1.MessageCommand[] GetMessageCommandsBySender(string path, string sender) {
            return base.Channel.GetMessageCommandsBySender(path, sender);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.MessageCommand[]> GetMessageCommandsBySenderAsync(string path, string sender) {
            return base.Channel.GetMessageCommandsBySenderAsync(path, sender);
        }
        
        public Markum.Cloud.Libraries.Service1.MessageCommand[] GetMessageCommandsByRecipient(string path, string recipient) {
            return base.Channel.GetMessageCommandsByRecipient(path, recipient);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.MessageCommand[]> GetMessageCommandsByRecipientAsync(string path, string recipient) {
            return base.Channel.GetMessageCommandsByRecipientAsync(path, recipient);
        }
        
        public Markum.Cloud.Libraries.Service1.MessageCommand[] GetMessageCommandsByClientIP(string path, string clientip) {
            return base.Channel.GetMessageCommandsByClientIP(path, clientip);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Service1.MessageCommand[]> GetMessageCommandsByClientIPAsync(string path, string clientip) {
            return base.Channel.GetMessageCommandsByClientIPAsync(path, clientip);
        }
        
        public string ReadMessageCommandFileText(string path, string filename) {
            return base.Channel.ReadMessageCommandFileText(path, filename);
        }
        
        public System.Threading.Tasks.Task<string> ReadMessageCommandFileTextAsync(string path, string filename) {
            return base.Channel.ReadMessageCommandFileTextAsync(path, filename);
        }
        
        public string ReadMessageFile(string path, string filename) {
            return base.Channel.ReadMessageFile(path, filename);
        }
        
        public System.Threading.Tasks.Task<string> ReadMessageFileAsync(string path, string filename) {
            return base.Channel.ReadMessageFileAsync(path, filename);
        }
        
        public string TestMe() {
            return base.Channel.TestMe();
        }
        
        public System.Threading.Tasks.Task<string> TestMeAsync() {
            return base.Channel.TestMeAsync();
        }
    }
}
