//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markum.Cloud.Libraries.Domain {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", ConfigurationName="Domain.DomainSoap")]
    public interface DomainSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/AddDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long AddDomain(string AccountName, string DomainName, long Status, string RedirectionHosts, long RedirectionStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/AddDomain", ReplyAction="*")]
        System.Threading.Tasks.Task<long> AddDomainAsync(string AccountName, string DomainName, long Status, string RedirectionHosts, long RedirectionStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/GetDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetDomain(string AccountName, string DomainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/GetDomain", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetDomainAsync(string AccountName, string DomainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/ListDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Domain.ListDomainResponse ListDomain(Markum.Cloud.Libraries.Domain.ListDomainRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/ListDomain", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Domain.ListDomainResponse> ListDomainAsync(Markum.Cloud.Libraries.Domain.ListDomainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/GetDomainObjectProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Domain.GetDomainObjectPropertiesResponse GetDomainObjectProperties(Markum.Cloud.Libraries.Domain.GetDomainObjectPropertiesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/GetDomainObjectProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Domain.GetDomainObjectPropertiesResponse> GetDomainObjectPropertiesAsync(Markum.Cloud.Libraries.Domain.GetDomainObjectPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/EditDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long EditDomain(string AccountName, string DomainName, string NewDomainName, long NewStatus, long NewRedirectionStatus, string NewRedirectionHosts, string NewAccountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/EditDomain", ReplyAction="*")]
        System.Threading.Tasks.Task<long> EditDomainAsync(string AccountName, string DomainName, string NewDomainName, long NewStatus, long NewRedirectionStatus, string NewRedirectionHosts, string NewAccountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/RemoveDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long RemoveDomain(string AccountName, string DomainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MEWebAdminService/Domain/RemoveDomain", ReplyAction="*")]
        System.Threading.Tasks.Task<long> RemoveDomainAsync(string AccountName, string DomainName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain")]
    public partial class Domain : MarshalByRefObject {
        
        private string domainNameField;
        
        private int statusField;
        
        private int domainRedirectionStatusField;
        
        private string domainRedirectionHostsField;
        
        private string accountNameField;
        
        private string hostField;
        
        private int retainModeField;
        
        private int pollForMessagesField;
        
        private string upStreamHostField;
        
        private int pollIntervalField;
        
        private int aliasModeField;
        
        private string aliasNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
                this.RaisePropertyChanged("DomainName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DomainRedirectionStatus {
            get {
                return this.domainRedirectionStatusField;
            }
            set {
                this.domainRedirectionStatusField = value;
                this.RaisePropertyChanged("DomainRedirectionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DomainRedirectionHosts {
            get {
                return this.domainRedirectionHostsField;
            }
            set {
                this.domainRedirectionHostsField = value;
                this.RaisePropertyChanged("DomainRedirectionHosts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
                this.RaisePropertyChanged("AccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
                this.RaisePropertyChanged("Host");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int RetainMode {
            get {
                return this.retainModeField;
            }
            set {
                this.retainModeField = value;
                this.RaisePropertyChanged("RetainMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int PollForMessages {
            get {
                return this.pollForMessagesField;
            }
            set {
                this.pollForMessagesField = value;
                this.RaisePropertyChanged("PollForMessages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UpStreamHost {
            get {
                return this.upStreamHostField;
            }
            set {
                this.upStreamHostField = value;
                this.RaisePropertyChanged("UpStreamHost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int PollInterval {
            get {
                return this.pollIntervalField;
            }
            set {
                this.pollIntervalField = value;
                this.RaisePropertyChanged("PollInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int AliasMode {
            get {
                return this.aliasModeField;
            }
            set {
                this.aliasModeField = value;
                this.RaisePropertyChanged("AliasMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AliasName {
            get {
                return this.aliasNameField;
            }
            set {
                this.aliasNameField = value;
                this.RaisePropertyChanged("AliasName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Domain))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListDomain", WrapperNamespace="http://tempuri.org/MEWebAdminService/Domain", IsWrapped=true)]
    public partial class ListDomainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=0)]
        public Markum.Cloud.Libraries.Domain.Domain[] ObjectList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=1)]
        public string AccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=2)]
        public string DomainName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=3)]
        public long Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=4)]
        public string DomainRedirectionHosts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=5)]
        public long DomainRedirectionStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=6)]
        public string MailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=7)]
        public long Top;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=8)]
        public long MaxLength;
        
        public ListDomainRequest() {
        }
        
        public ListDomainRequest(Markum.Cloud.Libraries.Domain.Domain[] ObjectList, string AccountName, string DomainName, long Status, string DomainRedirectionHosts, long DomainRedirectionStatus, string MailAddress, long Top, long MaxLength) {
            this.ObjectList = ObjectList;
            this.AccountName = AccountName;
            this.DomainName = DomainName;
            this.Status = Status;
            this.DomainRedirectionHosts = DomainRedirectionHosts;
            this.DomainRedirectionStatus = DomainRedirectionStatus;
            this.MailAddress = MailAddress;
            this.Top = Top;
            this.MaxLength = MaxLength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListDomainResponse", WrapperNamespace="http://tempuri.org/MEWebAdminService/Domain", IsWrapped=true)]
    public partial class ListDomainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=0)]
        public long ListDomainResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=1)]
        public Markum.Cloud.Libraries.Domain.Domain[] ObjectList;
        
        public ListDomainResponse() {
        }
        
        public ListDomainResponse(long ListDomainResult, Markum.Cloud.Libraries.Domain.Domain[] ObjectList) {
            this.ListDomainResult = ListDomainResult;
            this.ObjectList = ObjectList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDomainObjectProperties", WrapperNamespace="http://tempuri.org/MEWebAdminService/Domain", IsWrapped=true)]
    public partial class GetDomainObjectPropertiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=0)]
        public string AccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=1)]
        public string DomainName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=2)]
        public Markum.Cloud.Libraries.Domain.Domain ObjectProperties;
        
        public GetDomainObjectPropertiesRequest() {
        }
        
        public GetDomainObjectPropertiesRequest(string AccountName, string DomainName, Markum.Cloud.Libraries.Domain.Domain ObjectProperties) {
            this.AccountName = AccountName;
            this.DomainName = DomainName;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDomainObjectPropertiesResponse", WrapperNamespace="http://tempuri.org/MEWebAdminService/Domain", IsWrapped=true)]
    public partial class GetDomainObjectPropertiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=0)]
        public long GetDomainObjectPropertiesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/MEWebAdminService/Domain", Order=1)]
        public Markum.Cloud.Libraries.Domain.Domain ObjectProperties;
        
        public GetDomainObjectPropertiesResponse() {
        }
        
        public GetDomainObjectPropertiesResponse(long GetDomainObjectPropertiesResult, Markum.Cloud.Libraries.Domain.Domain ObjectProperties) {
            this.GetDomainObjectPropertiesResult = GetDomainObjectPropertiesResult;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DomainSoapChannel : Markum.Cloud.Libraries.Domain.DomainSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DomainSoapClient : System.ServiceModel.ClientBase<Markum.Cloud.Libraries.Domain.DomainSoap>, Markum.Cloud.Libraries.Domain.DomainSoap {
        
        public DomainSoapClient() {
        }
        
        public DomainSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DomainSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DomainSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DomainSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long AddDomain(string AccountName, string DomainName, long Status, string RedirectionHosts, long RedirectionStatus) {
            return base.Channel.AddDomain(AccountName, DomainName, Status, RedirectionHosts, RedirectionStatus);
        }
        
        public System.Threading.Tasks.Task<long> AddDomainAsync(string AccountName, string DomainName, long Status, string RedirectionHosts, long RedirectionStatus) {
            return base.Channel.AddDomainAsync(AccountName, DomainName, Status, RedirectionHosts, RedirectionStatus);
        }
        
        public long GetDomain(string AccountName, string DomainName) {
            return base.Channel.GetDomain(AccountName, DomainName);
        }
        
        public System.Threading.Tasks.Task<long> GetDomainAsync(string AccountName, string DomainName) {
            return base.Channel.GetDomainAsync(AccountName, DomainName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Domain.ListDomainResponse Markum.Cloud.Libraries.Domain.DomainSoap.ListDomain(Markum.Cloud.Libraries.Domain.ListDomainRequest request) {
            return base.Channel.ListDomain(request);
        }
        
        public long ListDomain(ref Markum.Cloud.Libraries.Domain.Domain[] ObjectList, string AccountName, string DomainName, long Status, string DomainRedirectionHosts, long DomainRedirectionStatus, string MailAddress, long Top, long MaxLength) {
            Markum.Cloud.Libraries.Domain.ListDomainRequest inValue = new Markum.Cloud.Libraries.Domain.ListDomainRequest();
            inValue.ObjectList = ObjectList;
            inValue.AccountName = AccountName;
            inValue.DomainName = DomainName;
            inValue.Status = Status;
            inValue.DomainRedirectionHosts = DomainRedirectionHosts;
            inValue.DomainRedirectionStatus = DomainRedirectionStatus;
            inValue.MailAddress = MailAddress;
            inValue.Top = Top;
            inValue.MaxLength = MaxLength;
            Markum.Cloud.Libraries.Domain.ListDomainResponse retVal = ((Markum.Cloud.Libraries.Domain.DomainSoap)(this)).ListDomain(inValue);
            ObjectList = retVal.ObjectList;
            return retVal.ListDomainResult;
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Domain.ListDomainResponse> ListDomainAsync(Markum.Cloud.Libraries.Domain.ListDomainRequest request) {
            return base.Channel.ListDomainAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Domain.GetDomainObjectPropertiesResponse Markum.Cloud.Libraries.Domain.DomainSoap.GetDomainObjectProperties(Markum.Cloud.Libraries.Domain.GetDomainObjectPropertiesRequest request) {
            return base.Channel.GetDomainObjectProperties(request);
        }
        
        public long GetDomainObjectProperties(string AccountName, string DomainName, ref Markum.Cloud.Libraries.Domain.Domain ObjectProperties) {
            Markum.Cloud.Libraries.Domain.GetDomainObjectPropertiesRequest inValue = new Markum.Cloud.Libraries.Domain.GetDomainObjectPropertiesRequest();
            inValue.AccountName = AccountName;
            inValue.DomainName = DomainName;
            inValue.ObjectProperties = ObjectProperties;
            Markum.Cloud.Libraries.Domain.GetDomainObjectPropertiesResponse retVal = ((Markum.Cloud.Libraries.Domain.DomainSoap)(this)).GetDomainObjectProperties(inValue);
            ObjectProperties = retVal.ObjectProperties;
            return retVal.GetDomainObjectPropertiesResult;
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Domain.GetDomainObjectPropertiesResponse> GetDomainObjectPropertiesAsync(Markum.Cloud.Libraries.Domain.GetDomainObjectPropertiesRequest request) {
            return base.Channel.GetDomainObjectPropertiesAsync(request);
        }
        
        public long EditDomain(string AccountName, string DomainName, string NewDomainName, long NewStatus, long NewRedirectionStatus, string NewRedirectionHosts, string NewAccountName) {
            return base.Channel.EditDomain(AccountName, DomainName, NewDomainName, NewStatus, NewRedirectionStatus, NewRedirectionHosts, NewAccountName);
        }
        
        public System.Threading.Tasks.Task<long> EditDomainAsync(string AccountName, string DomainName, string NewDomainName, long NewStatus, long NewRedirectionStatus, string NewRedirectionHosts, string NewAccountName) {
            return base.Channel.EditDomainAsync(AccountName, DomainName, NewDomainName, NewStatus, NewRedirectionStatus, NewRedirectionHosts, NewAccountName);
        }
        
        public long RemoveDomain(string AccountName, string DomainName) {
            return base.Channel.RemoveDomain(AccountName, DomainName);
        }
        
        public System.Threading.Tasks.Task<long> RemoveDomainAsync(string AccountName, string DomainName) {
            return base.Channel.RemoveDomainAsync(AccountName, DomainName);
        }
    }
}
