//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markum.Cloud.Libraries.Group {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", ConfigurationName="Group.GroupSoap")]
    public interface GroupSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/AddGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long AddGroup(string Postoffice, string GroupName, long GroupStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/AddGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<long> AddGroupAsync(string Postoffice, string GroupName, long GroupStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/GetGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetGroup(string Postoffice, string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/GetGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetGroupAsync(string Postoffice, string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/GetGroupObjectProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Group.GetGroupObjectPropertiesResponse GetGroupObjectProperties(Markum.Cloud.Libraries.Group.GetGroupObjectPropertiesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/GetGroupObjectProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Group.GetGroupObjectPropertiesResponse> GetGroupObjectPropertiesAsync(Markum.Cloud.Libraries.Group.GetGroupObjectPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/GroupList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Group.GroupListResponse GroupList(Markum.Cloud.Libraries.Group.GroupListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/GroupList", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Group.GroupListResponse> GroupListAsync(Markum.Cloud.Libraries.Group.GroupListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/RemoveGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long RemoveGroup(string Postoffice, string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/RemoveGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<long> RemoveGroupAsync(string Postoffice, string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/EditGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long EditGroup(string Postoffice, string GroupName, string NewGroupName, long NewGroupStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Group/EditGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<long> EditGroupAsync(string Postoffice, string GroupName, string NewGroupName, long NewGroupStatus);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group")]
    public partial class Group : MarshalByRefObject {
        
        private string recipientAddressField;
        
        private string postofficeField;
        
        private string groupNameField;
        
        private string groupFileField;
        
        private int groupStatusField;
        
        private string hostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecipientAddress {
            get {
                return this.recipientAddressField;
            }
            set {
                this.recipientAddressField = value;
                this.RaisePropertyChanged("RecipientAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Postoffice {
            get {
                return this.postofficeField;
            }
            set {
                this.postofficeField = value;
                this.RaisePropertyChanged("Postoffice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("GroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GroupFile {
            get {
                return this.groupFileField;
            }
            set {
                this.groupFileField = value;
                this.RaisePropertyChanged("GroupFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int GroupStatus {
            get {
                return this.groupStatusField;
            }
            set {
                this.groupStatusField = value;
                this.RaisePropertyChanged("GroupStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
                this.RaisePropertyChanged("Host");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGroupObjectProperties", WrapperNamespace="http://mailenable.com/MEWebAdminService/Group", IsWrapped=true)]
    public partial class GetGroupObjectPropertiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=0)]
        public string Postoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=1)]
        public string GroupName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=2)]
        public Markum.Cloud.Libraries.Group.Group ObjectProperties;
        
        public GetGroupObjectPropertiesRequest() {
        }
        
        public GetGroupObjectPropertiesRequest(string Postoffice, string GroupName, Markum.Cloud.Libraries.Group.Group ObjectProperties) {
            this.Postoffice = Postoffice;
            this.GroupName = GroupName;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGroupObjectPropertiesResponse", WrapperNamespace="http://mailenable.com/MEWebAdminService/Group", IsWrapped=true)]
    public partial class GetGroupObjectPropertiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=0)]
        public long GetGroupObjectPropertiesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=1)]
        public Markum.Cloud.Libraries.Group.Group ObjectProperties;
        
        public GetGroupObjectPropertiesResponse() {
        }
        
        public GetGroupObjectPropertiesResponse(long GetGroupObjectPropertiesResult, Markum.Cloud.Libraries.Group.Group ObjectProperties) {
            this.GetGroupObjectPropertiesResult = GetGroupObjectPropertiesResult;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GroupList", WrapperNamespace="http://mailenable.com/MEWebAdminService/Group", IsWrapped=true)]
    public partial class GroupListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=0)]
        public Markum.Cloud.Libraries.Group.Group[] ObjectList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=1)]
        public string Postoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=2)]
        public string GroupName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=3)]
        public long Top;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=4)]
        public long MaxLength;
        
        public GroupListRequest() {
        }
        
        public GroupListRequest(Markum.Cloud.Libraries.Group.Group[] ObjectList, string Postoffice, string GroupName, long Top, long MaxLength) {
            this.ObjectList = ObjectList;
            this.Postoffice = Postoffice;
            this.GroupName = GroupName;
            this.Top = Top;
            this.MaxLength = MaxLength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GroupListResponse", WrapperNamespace="http://mailenable.com/MEWebAdminService/Group", IsWrapped=true)]
    public partial class GroupListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=0)]
        public long GroupListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Group", Order=1)]
        public Markum.Cloud.Libraries.Group.Group[] ObjectList;
        
        public GroupListResponse() {
        }
        
        public GroupListResponse(long GroupListResult, Markum.Cloud.Libraries.Group.Group[] ObjectList) {
            this.GroupListResult = GroupListResult;
            this.ObjectList = ObjectList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GroupSoapChannel : Markum.Cloud.Libraries.Group.GroupSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupSoapClient : System.ServiceModel.ClientBase<Markum.Cloud.Libraries.Group.GroupSoap>, Markum.Cloud.Libraries.Group.GroupSoap {
        
        public GroupSoapClient() {
        }
        
        public GroupSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long AddGroup(string Postoffice, string GroupName, long GroupStatus) {
            return base.Channel.AddGroup(Postoffice, GroupName, GroupStatus);
        }
        
        public System.Threading.Tasks.Task<long> AddGroupAsync(string Postoffice, string GroupName, long GroupStatus) {
            return base.Channel.AddGroupAsync(Postoffice, GroupName, GroupStatus);
        }
        
        public long GetGroup(string Postoffice, string GroupName) {
            return base.Channel.GetGroup(Postoffice, GroupName);
        }
        
        public System.Threading.Tasks.Task<long> GetGroupAsync(string Postoffice, string GroupName) {
            return base.Channel.GetGroupAsync(Postoffice, GroupName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Group.GetGroupObjectPropertiesResponse Markum.Cloud.Libraries.Group.GroupSoap.GetGroupObjectProperties(Markum.Cloud.Libraries.Group.GetGroupObjectPropertiesRequest request) {
            return base.Channel.GetGroupObjectProperties(request);
        }
        
        public long GetGroupObjectProperties(string Postoffice, string GroupName, ref Markum.Cloud.Libraries.Group.Group ObjectProperties) {
            Markum.Cloud.Libraries.Group.GetGroupObjectPropertiesRequest inValue = new Markum.Cloud.Libraries.Group.GetGroupObjectPropertiesRequest();
            inValue.Postoffice = Postoffice;
            inValue.GroupName = GroupName;
            inValue.ObjectProperties = ObjectProperties;
            Markum.Cloud.Libraries.Group.GetGroupObjectPropertiesResponse retVal = ((Markum.Cloud.Libraries.Group.GroupSoap)(this)).GetGroupObjectProperties(inValue);
            ObjectProperties = retVal.ObjectProperties;
            return retVal.GetGroupObjectPropertiesResult;
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Group.GetGroupObjectPropertiesResponse> GetGroupObjectPropertiesAsync(Markum.Cloud.Libraries.Group.GetGroupObjectPropertiesRequest request) {
            return base.Channel.GetGroupObjectPropertiesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Group.GroupListResponse Markum.Cloud.Libraries.Group.GroupSoap.GroupList(Markum.Cloud.Libraries.Group.GroupListRequest request) {
            return base.Channel.GroupList(request);
        }
        
        public long GroupList(ref Markum.Cloud.Libraries.Group.Group[] ObjectList, string Postoffice, string GroupName, long Top, long MaxLength) {
            Markum.Cloud.Libraries.Group.GroupListRequest inValue = new Markum.Cloud.Libraries.Group.GroupListRequest();
            inValue.ObjectList = ObjectList;
            inValue.Postoffice = Postoffice;
            inValue.GroupName = GroupName;
            inValue.Top = Top;
            inValue.MaxLength = MaxLength;
            Markum.Cloud.Libraries.Group.GroupListResponse retVal = ((Markum.Cloud.Libraries.Group.GroupSoap)(this)).GroupList(inValue);
            ObjectList = retVal.ObjectList;
            return retVal.GroupListResult;
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Group.GroupListResponse> GroupListAsync(Markum.Cloud.Libraries.Group.GroupListRequest request) {
            return base.Channel.GroupListAsync(request);
        }
        
        public long RemoveGroup(string Postoffice, string GroupName) {
            return base.Channel.RemoveGroup(Postoffice, GroupName);
        }
        
        public System.Threading.Tasks.Task<long> RemoveGroupAsync(string Postoffice, string GroupName) {
            return base.Channel.RemoveGroupAsync(Postoffice, GroupName);
        }
        
        public long EditGroup(string Postoffice, string GroupName, string NewGroupName, long NewGroupStatus) {
            return base.Channel.EditGroup(Postoffice, GroupName, NewGroupName, NewGroupStatus);
        }
        
        public System.Threading.Tasks.Task<long> EditGroupAsync(string Postoffice, string GroupName, string NewGroupName, long NewGroupStatus) {
            return base.Channel.EditGroupAsync(Postoffice, GroupName, NewGroupName, NewGroupStatus);
        }
    }
}
