//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markum.Cloud.Libraries.Directory {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Directory", Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    [System.SerializableAttribute()]
    public partial class Directory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectoryEntryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectoryLocatorIDField;
        
        private int EntryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortOrderField;
        
        private int TopRecordField;
        
        private int RecordsPerPageField;
        
        private int NumRecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DirectoryEntryID {
            get {
                return this.DirectoryEntryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectoryEntryIDField, value) != true)) {
                    this.DirectoryEntryIDField = value;
                    this.RaisePropertyChanged("DirectoryEntryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MailAddress {
            get {
                return this.MailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.MailAddressField, value) != true)) {
                    this.MailAddressField = value;
                    this.RaisePropertyChanged("MailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DirectoryLocatorID {
            get {
                return this.DirectoryLocatorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectoryLocatorIDField, value) != true)) {
                    this.DirectoryLocatorIDField = value;
                    this.RaisePropertyChanged("DirectoryLocatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int EntryType {
            get {
                return this.EntryTypeField;
            }
            set {
                if ((this.EntryTypeField.Equals(value) != true)) {
                    this.EntryTypeField = value;
                    this.RaisePropertyChanged("EntryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Host {
            get {
                return this.HostField;
            }
            set {
                if ((object.ReferenceEquals(this.HostField, value) != true)) {
                    this.HostField = value;
                    this.RaisePropertyChanged("Host");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.SortOrderField, value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int TopRecord {
            get {
                return this.TopRecordField;
            }
            set {
                if ((this.TopRecordField.Equals(value) != true)) {
                    this.TopRecordField = value;
                    this.RaisePropertyChanged("TopRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int RecordsPerPage {
            get {
                return this.RecordsPerPageField;
            }
            set {
                if ((this.RecordsPerPageField.Equals(value) != true)) {
                    this.RecordsPerPageField = value;
                    this.RaisePropertyChanged("RecordsPerPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int NumRecords {
            get {
                return this.NumRecordsField;
            }
            set {
                if ((this.NumRecordsField.Equals(value) != true)) {
                    this.NumRecordsField = value;
                    this.RaisePropertyChanged("NumRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Filter {
            get {
                return this.FilterField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterField, value) != true)) {
                    this.FilterField = value;
                    this.RaisePropertyChanged("Filter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory", ConfigurationName="Directory.DirectorySoap")]
    public interface DirectorySoap {
        
        // CODEGEN: Generating message contract since element name PostOffice from namespace http://mailenable.com/MEWebAdminService/Directory is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/AddDirectory", ReplyAction="*")]
        Markum.Cloud.Libraries.Directory.AddDirectoryResponse AddDirectory(Markum.Cloud.Libraries.Directory.AddDirectoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/AddDirectory", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.AddDirectoryResponse> AddDirectoryAsync(Markum.Cloud.Libraries.Directory.AddDirectoryRequest request);
        
        // CODEGEN: Generating message contract since element name PostOffice from namespace http://mailenable.com/MEWebAdminService/Directory is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/GetDirectory", ReplyAction="*")]
        Markum.Cloud.Libraries.Directory.GetDirectoryResponse GetDirectory(Markum.Cloud.Libraries.Directory.GetDirectoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/GetDirectory", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.GetDirectoryResponse> GetDirectoryAsync(Markum.Cloud.Libraries.Directory.GetDirectoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/ListDirectory", ReplyAction="*")]
        Markum.Cloud.Libraries.Directory.ListDirectoryResponse ListDirectory(Markum.Cloud.Libraries.Directory.ListDirectoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/ListDirectory", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.ListDirectoryResponse> ListDirectoryAsync(Markum.Cloud.Libraries.Directory.ListDirectoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/GetDirectoryObjectProperties", ReplyAction="*")]
        Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesResponse GetDirectoryObjectProperties(Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/GetDirectoryObjectProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesResponse> GetDirectoryObjectPropertiesAsync(Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequest request);
        
        // CODEGEN: Generating message contract since element name PostOffice from namespace http://mailenable.com/MEWebAdminService/Directory is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/RemoveDirectory", ReplyAction="*")]
        Markum.Cloud.Libraries.Directory.RemoveDirectoryResponse RemoveDirectory(Markum.Cloud.Libraries.Directory.RemoveDirectoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/RemoveDirectory", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.RemoveDirectoryResponse> RemoveDirectoryAsync(Markum.Cloud.Libraries.Directory.RemoveDirectoryRequest request);
        
        // CODEGEN: Generating message contract since element name PostOffice from namespace http://mailenable.com/MEWebAdminService/Directory is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/EditDirectory", ReplyAction="*")]
        Markum.Cloud.Libraries.Directory.EditDirectoryResponse EditDirectory(Markum.Cloud.Libraries.Directory.EditDirectoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Directory/EditDirectory", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.EditDirectoryResponse> EditDirectoryAsync(Markum.Cloud.Libraries.Directory.EditDirectoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDirectory", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.AddDirectoryRequestBody Body;
        
        public AddDirectoryRequest() {
        }
        
        public AddDirectoryRequest(Markum.Cloud.Libraries.Directory.AddDirectoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class AddDirectoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostOffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MailAddress;
        
        public AddDirectoryRequestBody() {
        }
        
        public AddDirectoryRequestBody(string PostOffice, string DisplayName, string MailAddress) {
            this.PostOffice = PostOffice;
            this.DisplayName = DisplayName;
            this.MailAddress = MailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDirectoryResponse", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.AddDirectoryResponseBody Body;
        
        public AddDirectoryResponse() {
        }
        
        public AddDirectoryResponse(Markum.Cloud.Libraries.Directory.AddDirectoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class AddDirectoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long AddDirectoryResult;
        
        public AddDirectoryResponseBody() {
        }
        
        public AddDirectoryResponseBody(long AddDirectoryResult) {
            this.AddDirectoryResult = AddDirectoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDirectory", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.GetDirectoryRequestBody Body;
        
        public GetDirectoryRequest() {
        }
        
        public GetDirectoryRequest(Markum.Cloud.Libraries.Directory.GetDirectoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class GetDirectoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostOffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DirectoryEntryID;
        
        public GetDirectoryRequestBody() {
        }
        
        public GetDirectoryRequestBody(string PostOffice, string DirectoryEntryID) {
            this.PostOffice = PostOffice;
            this.DirectoryEntryID = DirectoryEntryID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDirectoryResponse", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.GetDirectoryResponseBody Body;
        
        public GetDirectoryResponse() {
        }
        
        public GetDirectoryResponse(Markum.Cloud.Libraries.Directory.GetDirectoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class GetDirectoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long GetDirectoryResult;
        
        public GetDirectoryResponseBody() {
        }
        
        public GetDirectoryResponseBody(long GetDirectoryResult) {
            this.GetDirectoryResult = GetDirectoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListDirectory", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.ListDirectoryRequestBody Body;
        
        public ListDirectoryRequest() {
        }
        
        public ListDirectoryRequest(Markum.Cloud.Libraries.Directory.ListDirectoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class ListDirectoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Markum.Cloud.Libraries.Directory.Directory[] ObjectList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Postoffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DirectoryEntryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DirectoryLocatorID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long EntryType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public long Top;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public long MaxLength;
        
        public ListDirectoryRequestBody() {
        }
        
        public ListDirectoryRequestBody(Markum.Cloud.Libraries.Directory.Directory[] ObjectList, string Postoffice, string DisplayName, string DirectoryEntryID, string DirectoryLocatorID, long EntryType, string MailAddress, long Top, long MaxLength) {
            this.ObjectList = ObjectList;
            this.Postoffice = Postoffice;
            this.DisplayName = DisplayName;
            this.DirectoryEntryID = DirectoryEntryID;
            this.DirectoryLocatorID = DirectoryLocatorID;
            this.EntryType = EntryType;
            this.MailAddress = MailAddress;
            this.Top = Top;
            this.MaxLength = MaxLength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListDirectoryResponse", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.ListDirectoryResponseBody Body;
        
        public ListDirectoryResponse() {
        }
        
        public ListDirectoryResponse(Markum.Cloud.Libraries.Directory.ListDirectoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class ListDirectoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long ListDirectoryResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Markum.Cloud.Libraries.Directory.Directory[] ObjectList;
        
        public ListDirectoryResponseBody() {
        }
        
        public ListDirectoryResponseBody(long ListDirectoryResult, Markum.Cloud.Libraries.Directory.Directory[] ObjectList) {
            this.ListDirectoryResult = ListDirectoryResult;
            this.ObjectList = ObjectList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDirectoryObjectPropertiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDirectoryObjectProperties", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequestBody Body;
        
        public GetDirectoryObjectPropertiesRequest() {
        }
        
        public GetDirectoryObjectPropertiesRequest(Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class GetDirectoryObjectPropertiesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostOffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DirectoryEntryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Markum.Cloud.Libraries.Directory.Directory ObjectProperties;
        
        public GetDirectoryObjectPropertiesRequestBody() {
        }
        
        public GetDirectoryObjectPropertiesRequestBody(string PostOffice, string DirectoryEntryID, Markum.Cloud.Libraries.Directory.Directory ObjectProperties) {
            this.PostOffice = PostOffice;
            this.DirectoryEntryID = DirectoryEntryID;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDirectoryObjectPropertiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDirectoryObjectPropertiesResponse", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesResponseBody Body;
        
        public GetDirectoryObjectPropertiesResponse() {
        }
        
        public GetDirectoryObjectPropertiesResponse(Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class GetDirectoryObjectPropertiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long GetDirectoryObjectPropertiesResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Markum.Cloud.Libraries.Directory.Directory ObjectProperties;
        
        public GetDirectoryObjectPropertiesResponseBody() {
        }
        
        public GetDirectoryObjectPropertiesResponseBody(long GetDirectoryObjectPropertiesResult, Markum.Cloud.Libraries.Directory.Directory ObjectProperties) {
            this.GetDirectoryObjectPropertiesResult = GetDirectoryObjectPropertiesResult;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveDirectory", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.RemoveDirectoryRequestBody Body;
        
        public RemoveDirectoryRequest() {
        }
        
        public RemoveDirectoryRequest(Markum.Cloud.Libraries.Directory.RemoveDirectoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class RemoveDirectoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostOffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DirectoryEntryID;
        
        public RemoveDirectoryRequestBody() {
        }
        
        public RemoveDirectoryRequestBody(string PostOffice, string MailAddress, string DirectoryEntryID) {
            this.PostOffice = PostOffice;
            this.MailAddress = MailAddress;
            this.DirectoryEntryID = DirectoryEntryID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveDirectoryResponse", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.RemoveDirectoryResponseBody Body;
        
        public RemoveDirectoryResponse() {
        }
        
        public RemoveDirectoryResponse(Markum.Cloud.Libraries.Directory.RemoveDirectoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class RemoveDirectoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long RemoveDirectoryResult;
        
        public RemoveDirectoryResponseBody() {
        }
        
        public RemoveDirectoryResponseBody(long RemoveDirectoryResult) {
            this.RemoveDirectoryResult = RemoveDirectoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditDirectory", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.EditDirectoryRequestBody Body;
        
        public EditDirectoryRequest() {
        }
        
        public EditDirectoryRequest(Markum.Cloud.Libraries.Directory.EditDirectoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class EditDirectoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostOffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DirectoryEntryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NewDirectoryEntryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NewEntryType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NewDirectoryLocatorID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NewPostOffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NewMailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NewDisplayName;
        
        public EditDirectoryRequestBody() {
        }
        
        public EditDirectoryRequestBody(string PostOffice, string DirectoryEntryID, string NewDirectoryEntryID, string NewEntryType, string NewDirectoryLocatorID, string NewPostOffice, string NewMailAddress, string NewDisplayName) {
            this.PostOffice = PostOffice;
            this.DirectoryEntryID = DirectoryEntryID;
            this.NewDirectoryEntryID = NewDirectoryEntryID;
            this.NewEntryType = NewEntryType;
            this.NewDirectoryLocatorID = NewDirectoryLocatorID;
            this.NewPostOffice = NewPostOffice;
            this.NewMailAddress = NewMailAddress;
            this.NewDisplayName = NewDisplayName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditDirectoryResponse", Namespace="http://mailenable.com/MEWebAdminService/Directory", Order=0)]
        public Markum.Cloud.Libraries.Directory.EditDirectoryResponseBody Body;
        
        public EditDirectoryResponse() {
        }
        
        public EditDirectoryResponse(Markum.Cloud.Libraries.Directory.EditDirectoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Directory")]
    public partial class EditDirectoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long EditDirectoryResult;
        
        public EditDirectoryResponseBody() {
        }
        
        public EditDirectoryResponseBody(long EditDirectoryResult) {
            this.EditDirectoryResult = EditDirectoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DirectorySoapChannel : Markum.Cloud.Libraries.Directory.DirectorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DirectorySoapClient : System.ServiceModel.ClientBase<Markum.Cloud.Libraries.Directory.DirectorySoap>, Markum.Cloud.Libraries.Directory.DirectorySoap {
        
        public DirectorySoapClient() {
        }
        
        public DirectorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DirectorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DirectorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DirectorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Directory.AddDirectoryResponse Markum.Cloud.Libraries.Directory.DirectorySoap.AddDirectory(Markum.Cloud.Libraries.Directory.AddDirectoryRequest request) {
            return base.Channel.AddDirectory(request);
        }
        
        public long AddDirectory(string PostOffice, string DisplayName, string MailAddress) {
            Markum.Cloud.Libraries.Directory.AddDirectoryRequest inValue = new Markum.Cloud.Libraries.Directory.AddDirectoryRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.AddDirectoryRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.DisplayName = DisplayName;
            inValue.Body.MailAddress = MailAddress;
            Markum.Cloud.Libraries.Directory.AddDirectoryResponse retVal = ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).AddDirectory(inValue);
            return retVal.Body.AddDirectoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.AddDirectoryResponse> Markum.Cloud.Libraries.Directory.DirectorySoap.AddDirectoryAsync(Markum.Cloud.Libraries.Directory.AddDirectoryRequest request) {
            return base.Channel.AddDirectoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.AddDirectoryResponse> AddDirectoryAsync(string PostOffice, string DisplayName, string MailAddress) {
            Markum.Cloud.Libraries.Directory.AddDirectoryRequest inValue = new Markum.Cloud.Libraries.Directory.AddDirectoryRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.AddDirectoryRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.DisplayName = DisplayName;
            inValue.Body.MailAddress = MailAddress;
            return ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).AddDirectoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Directory.GetDirectoryResponse Markum.Cloud.Libraries.Directory.DirectorySoap.GetDirectory(Markum.Cloud.Libraries.Directory.GetDirectoryRequest request) {
            return base.Channel.GetDirectory(request);
        }
        
        public long GetDirectory(string PostOffice, string DirectoryEntryID) {
            Markum.Cloud.Libraries.Directory.GetDirectoryRequest inValue = new Markum.Cloud.Libraries.Directory.GetDirectoryRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.GetDirectoryRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.DirectoryEntryID = DirectoryEntryID;
            Markum.Cloud.Libraries.Directory.GetDirectoryResponse retVal = ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).GetDirectory(inValue);
            return retVal.Body.GetDirectoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.GetDirectoryResponse> Markum.Cloud.Libraries.Directory.DirectorySoap.GetDirectoryAsync(Markum.Cloud.Libraries.Directory.GetDirectoryRequest request) {
            return base.Channel.GetDirectoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.GetDirectoryResponse> GetDirectoryAsync(string PostOffice, string DirectoryEntryID) {
            Markum.Cloud.Libraries.Directory.GetDirectoryRequest inValue = new Markum.Cloud.Libraries.Directory.GetDirectoryRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.GetDirectoryRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.DirectoryEntryID = DirectoryEntryID;
            return ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).GetDirectoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Directory.ListDirectoryResponse Markum.Cloud.Libraries.Directory.DirectorySoap.ListDirectory(Markum.Cloud.Libraries.Directory.ListDirectoryRequest request) {
            return base.Channel.ListDirectory(request);
        }
        
        public long ListDirectory(ref Markum.Cloud.Libraries.Directory.Directory[] ObjectList, string Postoffice, string DisplayName, string DirectoryEntryID, string DirectoryLocatorID, long EntryType, string MailAddress, long Top, long MaxLength) {
            Markum.Cloud.Libraries.Directory.ListDirectoryRequest inValue = new Markum.Cloud.Libraries.Directory.ListDirectoryRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.ListDirectoryRequestBody();
            inValue.Body.ObjectList = ObjectList;
            inValue.Body.Postoffice = Postoffice;
            inValue.Body.DisplayName = DisplayName;
            inValue.Body.DirectoryEntryID = DirectoryEntryID;
            inValue.Body.DirectoryLocatorID = DirectoryLocatorID;
            inValue.Body.EntryType = EntryType;
            inValue.Body.MailAddress = MailAddress;
            inValue.Body.Top = Top;
            inValue.Body.MaxLength = MaxLength;
            Markum.Cloud.Libraries.Directory.ListDirectoryResponse retVal = ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).ListDirectory(inValue);
            ObjectList = retVal.Body.ObjectList;
            return retVal.Body.ListDirectoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.ListDirectoryResponse> Markum.Cloud.Libraries.Directory.DirectorySoap.ListDirectoryAsync(Markum.Cloud.Libraries.Directory.ListDirectoryRequest request) {
            return base.Channel.ListDirectoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.ListDirectoryResponse> ListDirectoryAsync(Markum.Cloud.Libraries.Directory.Directory[] ObjectList, string Postoffice, string DisplayName, string DirectoryEntryID, string DirectoryLocatorID, long EntryType, string MailAddress, long Top, long MaxLength) {
            Markum.Cloud.Libraries.Directory.ListDirectoryRequest inValue = new Markum.Cloud.Libraries.Directory.ListDirectoryRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.ListDirectoryRequestBody();
            inValue.Body.ObjectList = ObjectList;
            inValue.Body.Postoffice = Postoffice;
            inValue.Body.DisplayName = DisplayName;
            inValue.Body.DirectoryEntryID = DirectoryEntryID;
            inValue.Body.DirectoryLocatorID = DirectoryLocatorID;
            inValue.Body.EntryType = EntryType;
            inValue.Body.MailAddress = MailAddress;
            inValue.Body.Top = Top;
            inValue.Body.MaxLength = MaxLength;
            return ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).ListDirectoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesResponse Markum.Cloud.Libraries.Directory.DirectorySoap.GetDirectoryObjectProperties(Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequest request) {
            return base.Channel.GetDirectoryObjectProperties(request);
        }
        
        public long GetDirectoryObjectProperties(string PostOffice, string DirectoryEntryID, ref Markum.Cloud.Libraries.Directory.Directory ObjectProperties) {
            Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequest inValue = new Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.DirectoryEntryID = DirectoryEntryID;
            inValue.Body.ObjectProperties = ObjectProperties;
            Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesResponse retVal = ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).GetDirectoryObjectProperties(inValue);
            ObjectProperties = retVal.Body.ObjectProperties;
            return retVal.Body.GetDirectoryObjectPropertiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesResponse> Markum.Cloud.Libraries.Directory.DirectorySoap.GetDirectoryObjectPropertiesAsync(Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequest request) {
            return base.Channel.GetDirectoryObjectPropertiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesResponse> GetDirectoryObjectPropertiesAsync(string PostOffice, string DirectoryEntryID, Markum.Cloud.Libraries.Directory.Directory ObjectProperties) {
            Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequest inValue = new Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.GetDirectoryObjectPropertiesRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.DirectoryEntryID = DirectoryEntryID;
            inValue.Body.ObjectProperties = ObjectProperties;
            return ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).GetDirectoryObjectPropertiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Directory.RemoveDirectoryResponse Markum.Cloud.Libraries.Directory.DirectorySoap.RemoveDirectory(Markum.Cloud.Libraries.Directory.RemoveDirectoryRequest request) {
            return base.Channel.RemoveDirectory(request);
        }
        
        public long RemoveDirectory(string PostOffice, string MailAddress, string DirectoryEntryID) {
            Markum.Cloud.Libraries.Directory.RemoveDirectoryRequest inValue = new Markum.Cloud.Libraries.Directory.RemoveDirectoryRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.RemoveDirectoryRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.MailAddress = MailAddress;
            inValue.Body.DirectoryEntryID = DirectoryEntryID;
            Markum.Cloud.Libraries.Directory.RemoveDirectoryResponse retVal = ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).RemoveDirectory(inValue);
            return retVal.Body.RemoveDirectoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.RemoveDirectoryResponse> Markum.Cloud.Libraries.Directory.DirectorySoap.RemoveDirectoryAsync(Markum.Cloud.Libraries.Directory.RemoveDirectoryRequest request) {
            return base.Channel.RemoveDirectoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.RemoveDirectoryResponse> RemoveDirectoryAsync(string PostOffice, string MailAddress, string DirectoryEntryID) {
            Markum.Cloud.Libraries.Directory.RemoveDirectoryRequest inValue = new Markum.Cloud.Libraries.Directory.RemoveDirectoryRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.RemoveDirectoryRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.MailAddress = MailAddress;
            inValue.Body.DirectoryEntryID = DirectoryEntryID;
            return ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).RemoveDirectoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Directory.EditDirectoryResponse Markum.Cloud.Libraries.Directory.DirectorySoap.EditDirectory(Markum.Cloud.Libraries.Directory.EditDirectoryRequest request) {
            return base.Channel.EditDirectory(request);
        }
        
        public long EditDirectory(string PostOffice, string DirectoryEntryID, string NewDirectoryEntryID, string NewEntryType, string NewDirectoryLocatorID, string NewPostOffice, string NewMailAddress, string NewDisplayName) {
            Markum.Cloud.Libraries.Directory.EditDirectoryRequest inValue = new Markum.Cloud.Libraries.Directory.EditDirectoryRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.EditDirectoryRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.DirectoryEntryID = DirectoryEntryID;
            inValue.Body.NewDirectoryEntryID = NewDirectoryEntryID;
            inValue.Body.NewEntryType = NewEntryType;
            inValue.Body.NewDirectoryLocatorID = NewDirectoryLocatorID;
            inValue.Body.NewPostOffice = NewPostOffice;
            inValue.Body.NewMailAddress = NewMailAddress;
            inValue.Body.NewDisplayName = NewDisplayName;
            Markum.Cloud.Libraries.Directory.EditDirectoryResponse retVal = ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).EditDirectory(inValue);
            return retVal.Body.EditDirectoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.EditDirectoryResponse> Markum.Cloud.Libraries.Directory.DirectorySoap.EditDirectoryAsync(Markum.Cloud.Libraries.Directory.EditDirectoryRequest request) {
            return base.Channel.EditDirectoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Directory.EditDirectoryResponse> EditDirectoryAsync(string PostOffice, string DirectoryEntryID, string NewDirectoryEntryID, string NewEntryType, string NewDirectoryLocatorID, string NewPostOffice, string NewMailAddress, string NewDisplayName) {
            Markum.Cloud.Libraries.Directory.EditDirectoryRequest inValue = new Markum.Cloud.Libraries.Directory.EditDirectoryRequest();
            inValue.Body = new Markum.Cloud.Libraries.Directory.EditDirectoryRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.DirectoryEntryID = DirectoryEntryID;
            inValue.Body.NewDirectoryEntryID = NewDirectoryEntryID;
            inValue.Body.NewEntryType = NewEntryType;
            inValue.Body.NewDirectoryLocatorID = NewDirectoryLocatorID;
            inValue.Body.NewPostOffice = NewPostOffice;
            inValue.Body.NewMailAddress = NewMailAddress;
            inValue.Body.NewDisplayName = NewDisplayName;
            return ((Markum.Cloud.Libraries.Directory.DirectorySoap)(this)).EditDirectoryAsync(inValue);
        }
    }
}
