//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markum.Cloud.Libraries.List {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", ConfigurationName="List.ListSoap")]
    public interface ListSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/AddList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long AddList(string Postoffice, string ListName, string Description, long Status, long ListType, string ModeratorAddress, string DefaultAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/AddList", ReplyAction="*")]
        System.Threading.Tasks.Task<long> AddListAsync(string Postoffice, string ListName, string Description, long Status, long ListType, string ModeratorAddress, string DefaultAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/GetList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetList(string Postoffice, string ListName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/GetList", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetListAsync(string Postoffice, string ListName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/GetListObjectProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.List.GetListObjectPropertiesResponse GetListObjectProperties(Markum.Cloud.Libraries.List.GetListObjectPropertiesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/GetListObjectProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.List.GetListObjectPropertiesResponse> GetListObjectPropertiesAsync(Markum.Cloud.Libraries.List.GetListObjectPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/ListList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.List.ListListResponse ListList(Markum.Cloud.Libraries.List.ListListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/ListList", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.List.ListListResponse> ListListAsync(Markum.Cloud.Libraries.List.ListListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/EditList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long EditList(string Postoffice, string ListName, string NewDescription, string NewAccountName, string NewListName, long NewListType, long NewStatus, long NewHeaderAnnotationStatus, string NewHeaderAnnotation, long NewFooterAnnotationStatus, string NewFooterAnnotation, string NewModeratorAddress, string NewDefaultAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/EditList", ReplyAction="*")]
        System.Threading.Tasks.Task<long> EditListAsync(string Postoffice, string ListName, string NewDescription, string NewAccountName, string NewListName, long NewListType, long NewStatus, long NewHeaderAnnotationStatus, string NewHeaderAnnotation, long NewFooterAnnotationStatus, string NewFooterAnnotation, string NewModeratorAddress, string NewDefaultAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/EditListFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long EditListFull(
                    string Postoffice, 
                    string ListName, 
                    string NewDescription, 
                    string NewAccountName, 
                    string NewListName, 
                    long NewListType, 
                    long NewStatus, 
                    long NewHeaderAnnotationStatus, 
                    string NewHeaderAnnotation, 
                    long NewFooterAnnotationStatus, 
                    string NewFooterAnnotation, 
                    string NewModeratorAddress, 
                    string NewDefaultAddress, 
                    long NewSubscribeMessageFileStatus, 
                    string NewSubscribeMessageFile, 
                    long NewUnsubscribeMessageFileStatus, 
                    string NewUnsubscribeMessageFile, 
                    long NewSubjectSuffixStatus, 
                    string NewSubjectSuffix, 
                    long NewSubjectPrefixStatus, 
                    string NewSubjectPrefix, 
                    string NewOwner, 
                    long NewHelpMessageFileStatus, 
                    string NewHelpMessageFile, 
                    long NewRemovalMessageFileStatus, 
                    string NewRemovalMessageFile, 
                    long NewReplyToMode, 
                    long NewMaxMessageSize, 
                    long NewPostingMode, 
                    long NewSubScriptionMode, 
                    long NewAuthenticationMode, 
                    string NewPassword, 
                    long NewDigestMode, 
                    string NewDigestMailbox, 
                    long NewDigestAnnotationMode, 
                    long NewDigestAttachmentMode, 
                    long NewDigestMessageSeparationMode, 
                    long NewDigestSchedulingStatus, 
                    long NewDigestSchedulingMode, 
                    long NewDigestSchedulingInterval, 
                    long NewFromAddressMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/EditListFull", ReplyAction="*")]
        System.Threading.Tasks.Task<long> EditListFullAsync(
                    string Postoffice, 
                    string ListName, 
                    string NewDescription, 
                    string NewAccountName, 
                    string NewListName, 
                    long NewListType, 
                    long NewStatus, 
                    long NewHeaderAnnotationStatus, 
                    string NewHeaderAnnotation, 
                    long NewFooterAnnotationStatus, 
                    string NewFooterAnnotation, 
                    string NewModeratorAddress, 
                    string NewDefaultAddress, 
                    long NewSubscribeMessageFileStatus, 
                    string NewSubscribeMessageFile, 
                    long NewUnsubscribeMessageFileStatus, 
                    string NewUnsubscribeMessageFile, 
                    long NewSubjectSuffixStatus, 
                    string NewSubjectSuffix, 
                    long NewSubjectPrefixStatus, 
                    string NewSubjectPrefix, 
                    string NewOwner, 
                    long NewHelpMessageFileStatus, 
                    string NewHelpMessageFile, 
                    long NewRemovalMessageFileStatus, 
                    string NewRemovalMessageFile, 
                    long NewReplyToMode, 
                    long NewMaxMessageSize, 
                    long NewPostingMode, 
                    long NewSubScriptionMode, 
                    long NewAuthenticationMode, 
                    string NewPassword, 
                    long NewDigestMode, 
                    string NewDigestMailbox, 
                    long NewDigestAnnotationMode, 
                    long NewDigestAttachmentMode, 
                    long NewDigestMessageSeparationMode, 
                    long NewDigestSchedulingStatus, 
                    long NewDigestSchedulingMode, 
                    long NewDigestSchedulingInterval, 
                    long NewFromAddressMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/RemoveList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long RemoveList(string Postoffice, string ListName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/RemoveList", ReplyAction="*")]
        System.Threading.Tasks.Task<long> RemoveListAsync(string Postoffice, string ListName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/GetHeader", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        string GetHeader(string Postoffice, string ListName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/GetHeader", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHeaderAsync(string Postoffice, string ListName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/GetFooter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        string GetFooter(string Postoffice, string ListName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/GetFooter", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetFooterAsync(string Postoffice, string ListName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/SetHeader", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long SetHeader(string Postoffice, string ListName, string ListHeader);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/SetHeader", ReplyAction="*")]
        System.Threading.Tasks.Task<long> SetHeaderAsync(string Postoffice, string ListName, string ListHeader);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/SetFooter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long SetFooter(string Postoffice, string ListName, string ListFooter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/List/SetFooter", ReplyAction="*")]
        System.Threading.Tasks.Task<long> SetFooterAsync(string Postoffice, string ListName, string ListFooter);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mailenable.com/MEWebAdminService/List")]
    public partial class List : MarshalByRefObject {
        
        private string hostField;
        
        private string descriptionField;
        
        private string accountNameField;
        
        private string listNameField;
        
        private long listTypeField;
        
        private long listStatusField;
        
        private string moderatorAddressField;
        
        private long headerAnnotationStatusField;
        
        private string headerAnnotationField;
        
        private long footerAnnotationStatusField;
        
        private string footerAnnotationField;
        
        private string listAddressField;
        
        private long subscribeMessageFileStatusField;
        
        private string subscribeMessageFileField;
        
        private long unsubscribeMessageFileStatusField;
        
        private string unsubscribeMessageFileField;
        
        private long subjectSuffixStatusField;
        
        private string subjectSuffixField;
        
        private long subjectPrefixStatusField;
        
        private string subjectPrefixField;
        
        private string ownerField;
        
        private long helpMessageFileStatusField;
        
        private string helpMessageFileField;
        
        private long removalMessageFileStatusField;
        
        private string removalMessageFileField;
        
        private long replyToModeField;
        
        private long maxMessageSizeField;
        
        private long postingModeField;
        
        private long subScriptionModeField;
        
        private long authenticationModeField;
        
        private string passwordField;
        
        private long digestModeField;
        
        private string digestMailboxField;
        
        private long digestAnnotationModeField;
        
        private long digestAttachmentModeField;
        
        private long digestMessageSeparationModeField;
        
        private long digestSchedulingStatusField;
        
        private long digestSchedulingModeField;
        
        private long digestSchedulingIntervalField;
        
        private long fromAddressModeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
                this.RaisePropertyChanged("Host");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
                this.RaisePropertyChanged("AccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ListName {
            get {
                return this.listNameField;
            }
            set {
                this.listNameField = value;
                this.RaisePropertyChanged("ListName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long ListType {
            get {
                return this.listTypeField;
            }
            set {
                this.listTypeField = value;
                this.RaisePropertyChanged("ListType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long ListStatus {
            get {
                return this.listStatusField;
            }
            set {
                this.listStatusField = value;
                this.RaisePropertyChanged("ListStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ModeratorAddress {
            get {
                return this.moderatorAddressField;
            }
            set {
                this.moderatorAddressField = value;
                this.RaisePropertyChanged("ModeratorAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long HeaderAnnotationStatus {
            get {
                return this.headerAnnotationStatusField;
            }
            set {
                this.headerAnnotationStatusField = value;
                this.RaisePropertyChanged("HeaderAnnotationStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string HeaderAnnotation {
            get {
                return this.headerAnnotationField;
            }
            set {
                this.headerAnnotationField = value;
                this.RaisePropertyChanged("HeaderAnnotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long FooterAnnotationStatus {
            get {
                return this.footerAnnotationStatusField;
            }
            set {
                this.footerAnnotationStatusField = value;
                this.RaisePropertyChanged("FooterAnnotationStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FooterAnnotation {
            get {
                return this.footerAnnotationField;
            }
            set {
                this.footerAnnotationField = value;
                this.RaisePropertyChanged("FooterAnnotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ListAddress {
            get {
                return this.listAddressField;
            }
            set {
                this.listAddressField = value;
                this.RaisePropertyChanged("ListAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public long SubscribeMessageFileStatus {
            get {
                return this.subscribeMessageFileStatusField;
            }
            set {
                this.subscribeMessageFileStatusField = value;
                this.RaisePropertyChanged("SubscribeMessageFileStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SubscribeMessageFile {
            get {
                return this.subscribeMessageFileField;
            }
            set {
                this.subscribeMessageFileField = value;
                this.RaisePropertyChanged("SubscribeMessageFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public long UnsubscribeMessageFileStatus {
            get {
                return this.unsubscribeMessageFileStatusField;
            }
            set {
                this.unsubscribeMessageFileStatusField = value;
                this.RaisePropertyChanged("UnsubscribeMessageFileStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string UnsubscribeMessageFile {
            get {
                return this.unsubscribeMessageFileField;
            }
            set {
                this.unsubscribeMessageFileField = value;
                this.RaisePropertyChanged("UnsubscribeMessageFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public long SubjectSuffixStatus {
            get {
                return this.subjectSuffixStatusField;
            }
            set {
                this.subjectSuffixStatusField = value;
                this.RaisePropertyChanged("SubjectSuffixStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string SubjectSuffix {
            get {
                return this.subjectSuffixField;
            }
            set {
                this.subjectSuffixField = value;
                this.RaisePropertyChanged("SubjectSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public long SubjectPrefixStatus {
            get {
                return this.subjectPrefixStatusField;
            }
            set {
                this.subjectPrefixStatusField = value;
                this.RaisePropertyChanged("SubjectPrefixStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SubjectPrefix {
            get {
                return this.subjectPrefixField;
            }
            set {
                this.subjectPrefixField = value;
                this.RaisePropertyChanged("SubjectPrefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public long HelpMessageFileStatus {
            get {
                return this.helpMessageFileStatusField;
            }
            set {
                this.helpMessageFileStatusField = value;
                this.RaisePropertyChanged("HelpMessageFileStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string HelpMessageFile {
            get {
                return this.helpMessageFileField;
            }
            set {
                this.helpMessageFileField = value;
                this.RaisePropertyChanged("HelpMessageFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public long RemovalMessageFileStatus {
            get {
                return this.removalMessageFileStatusField;
            }
            set {
                this.removalMessageFileStatusField = value;
                this.RaisePropertyChanged("RemovalMessageFileStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string RemovalMessageFile {
            get {
                return this.removalMessageFileField;
            }
            set {
                this.removalMessageFileField = value;
                this.RaisePropertyChanged("RemovalMessageFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public long ReplyToMode {
            get {
                return this.replyToModeField;
            }
            set {
                this.replyToModeField = value;
                this.RaisePropertyChanged("ReplyToMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public long MaxMessageSize {
            get {
                return this.maxMessageSizeField;
            }
            set {
                this.maxMessageSizeField = value;
                this.RaisePropertyChanged("MaxMessageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public long PostingMode {
            get {
                return this.postingModeField;
            }
            set {
                this.postingModeField = value;
                this.RaisePropertyChanged("PostingMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public long SubScriptionMode {
            get {
                return this.subScriptionModeField;
            }
            set {
                this.subScriptionModeField = value;
                this.RaisePropertyChanged("SubScriptionMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public long AuthenticationMode {
            get {
                return this.authenticationModeField;
            }
            set {
                this.authenticationModeField = value;
                this.RaisePropertyChanged("AuthenticationMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public long DigestMode {
            get {
                return this.digestModeField;
            }
            set {
                this.digestModeField = value;
                this.RaisePropertyChanged("DigestMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string DigestMailbox {
            get {
                return this.digestMailboxField;
            }
            set {
                this.digestMailboxField = value;
                this.RaisePropertyChanged("DigestMailbox");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public long DigestAnnotationMode {
            get {
                return this.digestAnnotationModeField;
            }
            set {
                this.digestAnnotationModeField = value;
                this.RaisePropertyChanged("DigestAnnotationMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public long DigestAttachmentMode {
            get {
                return this.digestAttachmentModeField;
            }
            set {
                this.digestAttachmentModeField = value;
                this.RaisePropertyChanged("DigestAttachmentMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public long DigestMessageSeparationMode {
            get {
                return this.digestMessageSeparationModeField;
            }
            set {
                this.digestMessageSeparationModeField = value;
                this.RaisePropertyChanged("DigestMessageSeparationMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public long DigestSchedulingStatus {
            get {
                return this.digestSchedulingStatusField;
            }
            set {
                this.digestSchedulingStatusField = value;
                this.RaisePropertyChanged("DigestSchedulingStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public long DigestSchedulingMode {
            get {
                return this.digestSchedulingModeField;
            }
            set {
                this.digestSchedulingModeField = value;
                this.RaisePropertyChanged("DigestSchedulingMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public long DigestSchedulingInterval {
            get {
                return this.digestSchedulingIntervalField;
            }
            set {
                this.digestSchedulingIntervalField = value;
                this.RaisePropertyChanged("DigestSchedulingInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public long FromAddressMode {
            get {
                return this.fromAddressModeField;
            }
            set {
                this.fromAddressModeField = value;
                this.RaisePropertyChanged("FromAddressMode");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(List))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mailenable.com/MEWebAdminService/List")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListObjectProperties", WrapperNamespace="http://mailenable.com/MEWebAdminService/List", IsWrapped=true)]
    public partial class GetListObjectPropertiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=0)]
        public string Postoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=1)]
        public string ListName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=2)]
        public Markum.Cloud.Libraries.List.List ObjectProperties;
        
        public GetListObjectPropertiesRequest() {
        }
        
        public GetListObjectPropertiesRequest(string Postoffice, string ListName, Markum.Cloud.Libraries.List.List ObjectProperties) {
            this.Postoffice = Postoffice;
            this.ListName = ListName;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListObjectPropertiesResponse", WrapperNamespace="http://mailenable.com/MEWebAdminService/List", IsWrapped=true)]
    public partial class GetListObjectPropertiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=0)]
        public long GetListObjectPropertiesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=1)]
        public Markum.Cloud.Libraries.List.List ObjectProperties;
        
        public GetListObjectPropertiesResponse() {
        }
        
        public GetListObjectPropertiesResponse(long GetListObjectPropertiesResult, Markum.Cloud.Libraries.List.List ObjectProperties) {
            this.GetListObjectPropertiesResult = GetListObjectPropertiesResult;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListList", WrapperNamespace="http://mailenable.com/MEWebAdminService/List", IsWrapped=true)]
    public partial class ListListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=0)]
        public Markum.Cloud.Libraries.List.List[] ObjectList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=1)]
        public string Postoffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=2)]
        public string ListName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=3)]
        public long Top;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=4)]
        public long MaxLength;
        
        public ListListRequest() {
        }
        
        public ListListRequest(Markum.Cloud.Libraries.List.List[] ObjectList, string Postoffice, string ListName, long Top, long MaxLength) {
            this.ObjectList = ObjectList;
            this.Postoffice = Postoffice;
            this.ListName = ListName;
            this.Top = Top;
            this.MaxLength = MaxLength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListListResponse", WrapperNamespace="http://mailenable.com/MEWebAdminService/List", IsWrapped=true)]
    public partial class ListListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=0)]
        public long ListListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/List", Order=1)]
        public Markum.Cloud.Libraries.List.List[] ObjectList;
        
        public ListListResponse() {
        }
        
        public ListListResponse(long ListListResult, Markum.Cloud.Libraries.List.List[] ObjectList) {
            this.ListListResult = ListListResult;
            this.ObjectList = ObjectList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ListSoapChannel : Markum.Cloud.Libraries.List.ListSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListSoapClient : System.ServiceModel.ClientBase<Markum.Cloud.Libraries.List.ListSoap>, Markum.Cloud.Libraries.List.ListSoap {
        
        public ListSoapClient() {
        }
        
        public ListSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long AddList(string Postoffice, string ListName, string Description, long Status, long ListType, string ModeratorAddress, string DefaultAddress) {
            return base.Channel.AddList(Postoffice, ListName, Description, Status, ListType, ModeratorAddress, DefaultAddress);
        }
        
        public System.Threading.Tasks.Task<long> AddListAsync(string Postoffice, string ListName, string Description, long Status, long ListType, string ModeratorAddress, string DefaultAddress) {
            return base.Channel.AddListAsync(Postoffice, ListName, Description, Status, ListType, ModeratorAddress, DefaultAddress);
        }
        
        public long GetList(string Postoffice, string ListName) {
            return base.Channel.GetList(Postoffice, ListName);
        }
        
        public System.Threading.Tasks.Task<long> GetListAsync(string Postoffice, string ListName) {
            return base.Channel.GetListAsync(Postoffice, ListName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.List.GetListObjectPropertiesResponse Markum.Cloud.Libraries.List.ListSoap.GetListObjectProperties(Markum.Cloud.Libraries.List.GetListObjectPropertiesRequest request) {
            return base.Channel.GetListObjectProperties(request);
        }
        
        public long GetListObjectProperties(string Postoffice, string ListName, ref Markum.Cloud.Libraries.List.List ObjectProperties) {
            Markum.Cloud.Libraries.List.GetListObjectPropertiesRequest inValue = new Markum.Cloud.Libraries.List.GetListObjectPropertiesRequest();
            inValue.Postoffice = Postoffice;
            inValue.ListName = ListName;
            inValue.ObjectProperties = ObjectProperties;
            Markum.Cloud.Libraries.List.GetListObjectPropertiesResponse retVal = ((Markum.Cloud.Libraries.List.ListSoap)(this)).GetListObjectProperties(inValue);
            ObjectProperties = retVal.ObjectProperties;
            return retVal.GetListObjectPropertiesResult;
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.List.GetListObjectPropertiesResponse> GetListObjectPropertiesAsync(Markum.Cloud.Libraries.List.GetListObjectPropertiesRequest request) {
            return base.Channel.GetListObjectPropertiesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.List.ListListResponse Markum.Cloud.Libraries.List.ListSoap.ListList(Markum.Cloud.Libraries.List.ListListRequest request) {
            return base.Channel.ListList(request);
        }
        
        public long ListList(ref Markum.Cloud.Libraries.List.List[] ObjectList, string Postoffice, string ListName, long Top, long MaxLength) {
            Markum.Cloud.Libraries.List.ListListRequest inValue = new Markum.Cloud.Libraries.List.ListListRequest();
            inValue.ObjectList = ObjectList;
            inValue.Postoffice = Postoffice;
            inValue.ListName = ListName;
            inValue.Top = Top;
            inValue.MaxLength = MaxLength;
            Markum.Cloud.Libraries.List.ListListResponse retVal = ((Markum.Cloud.Libraries.List.ListSoap)(this)).ListList(inValue);
            ObjectList = retVal.ObjectList;
            return retVal.ListListResult;
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.List.ListListResponse> ListListAsync(Markum.Cloud.Libraries.List.ListListRequest request) {
            return base.Channel.ListListAsync(request);
        }
        
        public long EditList(string Postoffice, string ListName, string NewDescription, string NewAccountName, string NewListName, long NewListType, long NewStatus, long NewHeaderAnnotationStatus, string NewHeaderAnnotation, long NewFooterAnnotationStatus, string NewFooterAnnotation, string NewModeratorAddress, string NewDefaultAddress) {
            return base.Channel.EditList(Postoffice, ListName, NewDescription, NewAccountName, NewListName, NewListType, NewStatus, NewHeaderAnnotationStatus, NewHeaderAnnotation, NewFooterAnnotationStatus, NewFooterAnnotation, NewModeratorAddress, NewDefaultAddress);
        }
        
        public System.Threading.Tasks.Task<long> EditListAsync(string Postoffice, string ListName, string NewDescription, string NewAccountName, string NewListName, long NewListType, long NewStatus, long NewHeaderAnnotationStatus, string NewHeaderAnnotation, long NewFooterAnnotationStatus, string NewFooterAnnotation, string NewModeratorAddress, string NewDefaultAddress) {
            return base.Channel.EditListAsync(Postoffice, ListName, NewDescription, NewAccountName, NewListName, NewListType, NewStatus, NewHeaderAnnotationStatus, NewHeaderAnnotation, NewFooterAnnotationStatus, NewFooterAnnotation, NewModeratorAddress, NewDefaultAddress);
        }
        
        public long EditListFull(
                    string Postoffice, 
                    string ListName, 
                    string NewDescription, 
                    string NewAccountName, 
                    string NewListName, 
                    long NewListType, 
                    long NewStatus, 
                    long NewHeaderAnnotationStatus, 
                    string NewHeaderAnnotation, 
                    long NewFooterAnnotationStatus, 
                    string NewFooterAnnotation, 
                    string NewModeratorAddress, 
                    string NewDefaultAddress, 
                    long NewSubscribeMessageFileStatus, 
                    string NewSubscribeMessageFile, 
                    long NewUnsubscribeMessageFileStatus, 
                    string NewUnsubscribeMessageFile, 
                    long NewSubjectSuffixStatus, 
                    string NewSubjectSuffix, 
                    long NewSubjectPrefixStatus, 
                    string NewSubjectPrefix, 
                    string NewOwner, 
                    long NewHelpMessageFileStatus, 
                    string NewHelpMessageFile, 
                    long NewRemovalMessageFileStatus, 
                    string NewRemovalMessageFile, 
                    long NewReplyToMode, 
                    long NewMaxMessageSize, 
                    long NewPostingMode, 
                    long NewSubScriptionMode, 
                    long NewAuthenticationMode, 
                    string NewPassword, 
                    long NewDigestMode, 
                    string NewDigestMailbox, 
                    long NewDigestAnnotationMode, 
                    long NewDigestAttachmentMode, 
                    long NewDigestMessageSeparationMode, 
                    long NewDigestSchedulingStatus, 
                    long NewDigestSchedulingMode, 
                    long NewDigestSchedulingInterval, 
                    long NewFromAddressMode) {
            return base.Channel.EditListFull(Postoffice, ListName, NewDescription, NewAccountName, NewListName, NewListType, NewStatus, NewHeaderAnnotationStatus, NewHeaderAnnotation, NewFooterAnnotationStatus, NewFooterAnnotation, NewModeratorAddress, NewDefaultAddress, NewSubscribeMessageFileStatus, NewSubscribeMessageFile, NewUnsubscribeMessageFileStatus, NewUnsubscribeMessageFile, NewSubjectSuffixStatus, NewSubjectSuffix, NewSubjectPrefixStatus, NewSubjectPrefix, NewOwner, NewHelpMessageFileStatus, NewHelpMessageFile, NewRemovalMessageFileStatus, NewRemovalMessageFile, NewReplyToMode, NewMaxMessageSize, NewPostingMode, NewSubScriptionMode, NewAuthenticationMode, NewPassword, NewDigestMode, NewDigestMailbox, NewDigestAnnotationMode, NewDigestAttachmentMode, NewDigestMessageSeparationMode, NewDigestSchedulingStatus, NewDigestSchedulingMode, NewDigestSchedulingInterval, NewFromAddressMode);
        }
        
        public System.Threading.Tasks.Task<long> EditListFullAsync(
                    string Postoffice, 
                    string ListName, 
                    string NewDescription, 
                    string NewAccountName, 
                    string NewListName, 
                    long NewListType, 
                    long NewStatus, 
                    long NewHeaderAnnotationStatus, 
                    string NewHeaderAnnotation, 
                    long NewFooterAnnotationStatus, 
                    string NewFooterAnnotation, 
                    string NewModeratorAddress, 
                    string NewDefaultAddress, 
                    long NewSubscribeMessageFileStatus, 
                    string NewSubscribeMessageFile, 
                    long NewUnsubscribeMessageFileStatus, 
                    string NewUnsubscribeMessageFile, 
                    long NewSubjectSuffixStatus, 
                    string NewSubjectSuffix, 
                    long NewSubjectPrefixStatus, 
                    string NewSubjectPrefix, 
                    string NewOwner, 
                    long NewHelpMessageFileStatus, 
                    string NewHelpMessageFile, 
                    long NewRemovalMessageFileStatus, 
                    string NewRemovalMessageFile, 
                    long NewReplyToMode, 
                    long NewMaxMessageSize, 
                    long NewPostingMode, 
                    long NewSubScriptionMode, 
                    long NewAuthenticationMode, 
                    string NewPassword, 
                    long NewDigestMode, 
                    string NewDigestMailbox, 
                    long NewDigestAnnotationMode, 
                    long NewDigestAttachmentMode, 
                    long NewDigestMessageSeparationMode, 
                    long NewDigestSchedulingStatus, 
                    long NewDigestSchedulingMode, 
                    long NewDigestSchedulingInterval, 
                    long NewFromAddressMode) {
            return base.Channel.EditListFullAsync(Postoffice, ListName, NewDescription, NewAccountName, NewListName, NewListType, NewStatus, NewHeaderAnnotationStatus, NewHeaderAnnotation, NewFooterAnnotationStatus, NewFooterAnnotation, NewModeratorAddress, NewDefaultAddress, NewSubscribeMessageFileStatus, NewSubscribeMessageFile, NewUnsubscribeMessageFileStatus, NewUnsubscribeMessageFile, NewSubjectSuffixStatus, NewSubjectSuffix, NewSubjectPrefixStatus, NewSubjectPrefix, NewOwner, NewHelpMessageFileStatus, NewHelpMessageFile, NewRemovalMessageFileStatus, NewRemovalMessageFile, NewReplyToMode, NewMaxMessageSize, NewPostingMode, NewSubScriptionMode, NewAuthenticationMode, NewPassword, NewDigestMode, NewDigestMailbox, NewDigestAnnotationMode, NewDigestAttachmentMode, NewDigestMessageSeparationMode, NewDigestSchedulingStatus, NewDigestSchedulingMode, NewDigestSchedulingInterval, NewFromAddressMode);
        }
        
        public long RemoveList(string Postoffice, string ListName) {
            return base.Channel.RemoveList(Postoffice, ListName);
        }
        
        public System.Threading.Tasks.Task<long> RemoveListAsync(string Postoffice, string ListName) {
            return base.Channel.RemoveListAsync(Postoffice, ListName);
        }
        
        public string GetHeader(string Postoffice, string ListName) {
            return base.Channel.GetHeader(Postoffice, ListName);
        }
        
        public System.Threading.Tasks.Task<string> GetHeaderAsync(string Postoffice, string ListName) {
            return base.Channel.GetHeaderAsync(Postoffice, ListName);
        }
        
        public string GetFooter(string Postoffice, string ListName) {
            return base.Channel.GetFooter(Postoffice, ListName);
        }
        
        public System.Threading.Tasks.Task<string> GetFooterAsync(string Postoffice, string ListName) {
            return base.Channel.GetFooterAsync(Postoffice, ListName);
        }
        
        public long SetHeader(string Postoffice, string ListName, string ListHeader) {
            return base.Channel.SetHeader(Postoffice, ListName, ListHeader);
        }
        
        public System.Threading.Tasks.Task<long> SetHeaderAsync(string Postoffice, string ListName, string ListHeader) {
            return base.Channel.SetHeaderAsync(Postoffice, ListName, ListHeader);
        }
        
        public long SetFooter(string Postoffice, string ListName, string ListFooter) {
            return base.Channel.SetFooter(Postoffice, ListName, ListFooter);
        }
        
        public System.Threading.Tasks.Task<long> SetFooterAsync(string Postoffice, string ListName, string ListFooter) {
            return base.Channel.SetFooterAsync(Postoffice, ListName, ListFooter);
        }
    }
}
