//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markum.Cloud.Libraries.SystemOptions {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/SystemOptions", ConfigurationName="SystemOptions.SystemOptionsSoap")]
    public interface SystemOptionsSoap {
        
        // CODEGEN: Generating message contract since element name PostOffice from namespace http://mailenable.com/MEWebAdminService/SystemOptions is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/SystemOptions/GetOption", ReplyAction="*")]
        Markum.Cloud.Libraries.SystemOptions.GetOptionResponse GetOption(Markum.Cloud.Libraries.SystemOptions.GetOptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/SystemOptions/GetOption", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.SystemOptions.GetOptionResponse> GetOptionAsync(Markum.Cloud.Libraries.SystemOptions.GetOptionRequest request);
        
        // CODEGEN: Generating message contract since element name PostOffice from namespace http://mailenable.com/MEWebAdminService/SystemOptions is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/SystemOptions/SetOption", ReplyAction="*")]
        Markum.Cloud.Libraries.SystemOptions.SetOptionResponse SetOption(Markum.Cloud.Libraries.SystemOptions.SetOptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/SystemOptions/SetOption", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.SystemOptions.SetOptionResponse> SetOptionAsync(Markum.Cloud.Libraries.SystemOptions.SetOptionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOption", Namespace="http://mailenable.com/MEWebAdminService/SystemOptions", Order=0)]
        public Markum.Cloud.Libraries.SystemOptions.GetOptionRequestBody Body;
        
        public GetOptionRequest() {
        }
        
        public GetOptionRequest(Markum.Cloud.Libraries.SystemOptions.GetOptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/SystemOptions")]
    public partial class GetOptionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostOffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long Scope;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ValueName;
        
        public GetOptionRequestBody() {
        }
        
        public GetOptionRequestBody(string PostOffice, long Scope, string ValueName) {
            this.PostOffice = PostOffice;
            this.Scope = Scope;
            this.ValueName = ValueName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOptionResponse", Namespace="http://mailenable.com/MEWebAdminService/SystemOptions", Order=0)]
        public Markum.Cloud.Libraries.SystemOptions.GetOptionResponseBody Body;
        
        public GetOptionResponse() {
        }
        
        public GetOptionResponse(Markum.Cloud.Libraries.SystemOptions.GetOptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/SystemOptions")]
    public partial class GetOptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long GetOptionResult;
        
        public GetOptionResponseBody() {
        }
        
        public GetOptionResponseBody(long GetOptionResult) {
            this.GetOptionResult = GetOptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetOptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetOption", Namespace="http://mailenable.com/MEWebAdminService/SystemOptions", Order=0)]
        public Markum.Cloud.Libraries.SystemOptions.SetOptionRequestBody Body;
        
        public SetOptionRequest() {
        }
        
        public SetOptionRequest(Markum.Cloud.Libraries.SystemOptions.SetOptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/SystemOptions")]
    public partial class SetOptionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostOffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long Scope;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ValueName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Value;
        
        public SetOptionRequestBody() {
        }
        
        public SetOptionRequestBody(string PostOffice, long Scope, string ValueName, string Value) {
            this.PostOffice = PostOffice;
            this.Scope = Scope;
            this.ValueName = ValueName;
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetOptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetOptionResponse", Namespace="http://mailenable.com/MEWebAdminService/SystemOptions", Order=0)]
        public Markum.Cloud.Libraries.SystemOptions.SetOptionResponseBody Body;
        
        public SetOptionResponse() {
        }
        
        public SetOptionResponse(Markum.Cloud.Libraries.SystemOptions.SetOptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/SystemOptions")]
    public partial class SetOptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long SetOptionResult;
        
        public SetOptionResponseBody() {
        }
        
        public SetOptionResponseBody(long SetOptionResult) {
            this.SetOptionResult = SetOptionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SystemOptionsSoapChannel : Markum.Cloud.Libraries.SystemOptions.SystemOptionsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemOptionsSoapClient : System.ServiceModel.ClientBase<Markum.Cloud.Libraries.SystemOptions.SystemOptionsSoap>, Markum.Cloud.Libraries.SystemOptions.SystemOptionsSoap {
        
        public SystemOptionsSoapClient() {
        }
        
        public SystemOptionsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemOptionsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemOptionsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemOptionsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.SystemOptions.GetOptionResponse Markum.Cloud.Libraries.SystemOptions.SystemOptionsSoap.GetOption(Markum.Cloud.Libraries.SystemOptions.GetOptionRequest request) {
            return base.Channel.GetOption(request);
        }
        
        public long GetOption(string PostOffice, long Scope, string ValueName) {
            Markum.Cloud.Libraries.SystemOptions.GetOptionRequest inValue = new Markum.Cloud.Libraries.SystemOptions.GetOptionRequest();
            inValue.Body = new Markum.Cloud.Libraries.SystemOptions.GetOptionRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.Scope = Scope;
            inValue.Body.ValueName = ValueName;
            Markum.Cloud.Libraries.SystemOptions.GetOptionResponse retVal = ((Markum.Cloud.Libraries.SystemOptions.SystemOptionsSoap)(this)).GetOption(inValue);
            return retVal.Body.GetOptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.SystemOptions.GetOptionResponse> Markum.Cloud.Libraries.SystemOptions.SystemOptionsSoap.GetOptionAsync(Markum.Cloud.Libraries.SystemOptions.GetOptionRequest request) {
            return base.Channel.GetOptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.SystemOptions.GetOptionResponse> GetOptionAsync(string PostOffice, long Scope, string ValueName) {
            Markum.Cloud.Libraries.SystemOptions.GetOptionRequest inValue = new Markum.Cloud.Libraries.SystemOptions.GetOptionRequest();
            inValue.Body = new Markum.Cloud.Libraries.SystemOptions.GetOptionRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.Scope = Scope;
            inValue.Body.ValueName = ValueName;
            return ((Markum.Cloud.Libraries.SystemOptions.SystemOptionsSoap)(this)).GetOptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.SystemOptions.SetOptionResponse Markum.Cloud.Libraries.SystemOptions.SystemOptionsSoap.SetOption(Markum.Cloud.Libraries.SystemOptions.SetOptionRequest request) {
            return base.Channel.SetOption(request);
        }
        
        public long SetOption(string PostOffice, long Scope, string ValueName, string Value) {
            Markum.Cloud.Libraries.SystemOptions.SetOptionRequest inValue = new Markum.Cloud.Libraries.SystemOptions.SetOptionRequest();
            inValue.Body = new Markum.Cloud.Libraries.SystemOptions.SetOptionRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.Scope = Scope;
            inValue.Body.ValueName = ValueName;
            inValue.Body.Value = Value;
            Markum.Cloud.Libraries.SystemOptions.SetOptionResponse retVal = ((Markum.Cloud.Libraries.SystemOptions.SystemOptionsSoap)(this)).SetOption(inValue);
            return retVal.Body.SetOptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.SystemOptions.SetOptionResponse> Markum.Cloud.Libraries.SystemOptions.SystemOptionsSoap.SetOptionAsync(Markum.Cloud.Libraries.SystemOptions.SetOptionRequest request) {
            return base.Channel.SetOptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.SystemOptions.SetOptionResponse> SetOptionAsync(string PostOffice, long Scope, string ValueName, string Value) {
            Markum.Cloud.Libraries.SystemOptions.SetOptionRequest inValue = new Markum.Cloud.Libraries.SystemOptions.SetOptionRequest();
            inValue.Body = new Markum.Cloud.Libraries.SystemOptions.SetOptionRequestBody();
            inValue.Body.PostOffice = PostOffice;
            inValue.Body.Scope = Scope;
            inValue.Body.ValueName = ValueName;
            inValue.Body.Value = Value;
            return ((Markum.Cloud.Libraries.SystemOptions.SystemOptionsSoap)(this)).SetOptionAsync(inValue);
        }
    }
}
