"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var sidebar_metadata_1 = require("./sidebar.metadata");
exports.ROUTES = [
    { path: 'dashboard', title: 'Main Page', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'material-icons' },
    { path: 'accounts/account', title: 'My Account', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'material-icons' },
    { path: 'accounts/accsetting', title: 'Settings', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'material-icons' },
    { path: 'hostings/webhosting', title: 'Web Hosting Hesapları', menuType: sidebar_metadata_1.MenuType.LEFT, icon: '' },
    { path: 'hostings/adddomain', title: 'Domain Ekle', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-plugin' },
    { path: 'hostings/addsubdomain', title: 'Alt Domain Ekle', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-plugin' },
    { path: 'hostings/plans', title: 'Planlar', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-plugin' },
    { path: 'domains/outtransfer', title: 'Dış Transfer', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-plugin' },
    { path: 'domains/intransfer', title: 'İç Transfer', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-plugin' },
    { path: 'domains/parking', title: 'Parking Hizmeti', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-plugin' },
    { path: 'domains/relocate', title: 'Yönlendirme', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-plugin' },
    { path: 'domains/dns', title: 'Dns', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-plugin' },
    { path: 'mails/mailhostingaccount', title: 'Mail Hosting Hesapları', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-note2' },
    { path: 'mails/addmaildomain', title: 'Mail Domain Ekleme', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-note2' },
    { path: 'mails/mailplans', title: 'Planlar', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-note2' },
    { path: 'server/servers', title: 'Sunucular', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-note2' },
    { path: 'server/addserver', title: 'Sunucu Ekle', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-news-paper' },
    { path: 'server/serverplans', title: 'Planlar', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-news-paper' },
    { path: 'database/databases', title: 'Veritabanları', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-news-paper' },
    { path: 'database/adddatabase', title: 'Veritabanı Ekle', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-map-marker' },
    { path: 'database/databaseplans', title: 'Planlar', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-map-marker' },
    { path: 'ssl/ssls', title: 'Sertifikalar', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-news-paper' },
    { path: 'ssl/addssl', title: 'Sertifika Ekle', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-map-marker' },
    { path: 'ssl/sslplans', title: 'Planlar', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-map-marker' },
    { path: 'licence/licences', title: 'Lisanslar', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-map-marker' },
    { path: 'licence/addlicence', title: 'Lisans Ekle', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-news-paper' },
    { path: 'licence/licenceplans', title: 'Lisans Planları', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-map-marker' },
    { path: 'ticket/addticket', title: 'Ticket Ekle', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-news-paper' },
    { path: 'ticket/ticketdevelopment', title: 'Geliştirme Talepleri', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-map-marker' },
    { path: 'ticket/tickethelp', title: 'Yardım', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-map-marker' },
    { path: 'cloudservice/addcloudservice', title: 'Bulut Servis Ekle', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-news-paper' },
    { path: 'cloudservice/cloudserviceplans', title: 'Bulut Servis Planları', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-news-paper' },
    { path: 'cloudservice/cloudservices', title: 'Bulut Servisler', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-news-paper' },
    { path: 'refreshprocess/servicerefresh', title: 'Hizmet Yenileme', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-news-paper' },
    { path: 'refreshprocess/domainrefresh', title: 'Domain Yenileme', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'pe-7s-map-marker' },
    //{ path: 'maps/vector', title: 'Vector Map', menuType: MenuType.LEFT, icon:'pe-7s-map-marker' },
    { path: 'widges', title: 'Widges', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'material-icons' },
    { path: 'charts', title: 'Charts', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'material-icons' },
    { path: 'calendar', title: 'Calendar', menuType: sidebar_metadata_1.MenuType.LEFT, icon: 'material-icons' },
];
//# sourceMappingURL=sidebar-routes.config.js.map