//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markum.Cloud.Libraries.Login {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", ConfigurationName="Login.LoginSoap")]
    public interface LoginSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/AddLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long AddLogin(string PostOffice, string Username, string Password, string Description, long Status, string Rights);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/AddLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<long> AddLoginAsync(string PostOffice, string Username, string Password, string Description, long Status, string Rights);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/GetLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetLogin(string PostOffice, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/GetLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetLoginAsync(string PostOffice, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/GetLoginObjectProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Login.GetLoginObjectPropertiesResponse GetLoginObjectProperties(Markum.Cloud.Libraries.Login.GetLoginObjectPropertiesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/GetLoginObjectProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Login.GetLoginObjectPropertiesResponse> GetLoginObjectPropertiesAsync(Markum.Cloud.Libraries.Login.GetLoginObjectPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/ListLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        Markum.Cloud.Libraries.Login.ListLoginResponse ListLogin(Markum.Cloud.Libraries.Login.ListLoginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/ListLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<Markum.Cloud.Libraries.Login.ListLoginResponse> ListLoginAsync(Markum.Cloud.Libraries.Login.ListLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/RemoveLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long RemoveLogin(string PostOffice, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/RemoveLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<long> RemoveLoginAsync(string PostOffice, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/EditLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        long EditLogin(string PostOffice, string Username, string NewPostOffice, string NewUsername, string NewPassword, long NewStatus, string NewDescription, string NewRights);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mailenable.com/MEWebAdminService/Login/EditLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<long> EditLoginAsync(string PostOffice, string Username, string NewPostOffice, string NewUsername, string NewPassword, long NewStatus, string NewDescription, string NewRights);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login")]
    public partial class Login : MarshalByRefObject {
        
        private string userNameField;
        
        private long statusField;
        
        private string passwordField;
        
        private string accountField;
        
        private string descriptionField;
        
        private long loginAttemptsField;
        
        private long lastAttemptField;
        
        private long lastSuccessfulLoginField;
        
        private string rightsField;
        
        private string hostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("Account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long LoginAttempts {
            get {
                return this.loginAttemptsField;
            }
            set {
                this.loginAttemptsField = value;
                this.RaisePropertyChanged("LoginAttempts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long LastAttempt {
            get {
                return this.lastAttemptField;
            }
            set {
                this.lastAttemptField = value;
                this.RaisePropertyChanged("LastAttempt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long LastSuccessfulLogin {
            get {
                return this.lastSuccessfulLoginField;
            }
            set {
                this.lastSuccessfulLoginField = value;
                this.RaisePropertyChanged("LastSuccessfulLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Rights {
            get {
                return this.rightsField;
            }
            set {
                this.rightsField = value;
                this.RaisePropertyChanged("Rights");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
                this.RaisePropertyChanged("Host");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Login))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLoginObjectProperties", WrapperNamespace="http://mailenable.com/MEWebAdminService/Login", IsWrapped=true)]
    public partial class GetLoginObjectPropertiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=0)]
        public string PostOffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=2)]
        public Markum.Cloud.Libraries.Login.Login ObjectProperties;
        
        public GetLoginObjectPropertiesRequest() {
        }
        
        public GetLoginObjectPropertiesRequest(string PostOffice, string Username, Markum.Cloud.Libraries.Login.Login ObjectProperties) {
            this.PostOffice = PostOffice;
            this.Username = Username;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLoginObjectPropertiesResponse", WrapperNamespace="http://mailenable.com/MEWebAdminService/Login", IsWrapped=true)]
    public partial class GetLoginObjectPropertiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=0)]
        public long GetLoginObjectPropertiesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=1)]
        public Markum.Cloud.Libraries.Login.Login ObjectProperties;
        
        public GetLoginObjectPropertiesResponse() {
        }
        
        public GetLoginObjectPropertiesResponse(long GetLoginObjectPropertiesResult, Markum.Cloud.Libraries.Login.Login ObjectProperties) {
            this.GetLoginObjectPropertiesResult = GetLoginObjectPropertiesResult;
            this.ObjectProperties = ObjectProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListLogin", WrapperNamespace="http://mailenable.com/MEWebAdminService/Login", IsWrapped=true)]
    public partial class ListLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=0)]
        public Markum.Cloud.Libraries.Login.Login[] ObjectList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=1)]
        public string PostOffice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=2)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=3)]
        public long Top;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=4)]
        public long MaxLength;
        
        public ListLoginRequest() {
        }
        
        public ListLoginRequest(Markum.Cloud.Libraries.Login.Login[] ObjectList, string PostOffice, string Username, long Top, long MaxLength) {
            this.ObjectList = ObjectList;
            this.PostOffice = PostOffice;
            this.Username = Username;
            this.Top = Top;
            this.MaxLength = MaxLength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListLoginResponse", WrapperNamespace="http://mailenable.com/MEWebAdminService/Login", IsWrapped=true)]
    public partial class ListLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=0)]
        public long ListLoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mailenable.com/MEWebAdminService/Login", Order=1)]
        public Markum.Cloud.Libraries.Login.Login[] ObjectList;
        
        public ListLoginResponse() {
        }
        
        public ListLoginResponse(long ListLoginResult, Markum.Cloud.Libraries.Login.Login[] ObjectList) {
            this.ListLoginResult = ListLoginResult;
            this.ObjectList = ObjectList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginSoapChannel : Markum.Cloud.Libraries.Login.LoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginSoapClient : System.ServiceModel.ClientBase<Markum.Cloud.Libraries.Login.LoginSoap>, Markum.Cloud.Libraries.Login.LoginSoap {
        
        public LoginSoapClient() {
        }
        
        public LoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long AddLogin(string PostOffice, string Username, string Password, string Description, long Status, string Rights) {
            return base.Channel.AddLogin(PostOffice, Username, Password, Description, Status, Rights);
        }
        
        public System.Threading.Tasks.Task<long> AddLoginAsync(string PostOffice, string Username, string Password, string Description, long Status, string Rights) {
            return base.Channel.AddLoginAsync(PostOffice, Username, Password, Description, Status, Rights);
        }
        
        public long GetLogin(string PostOffice, string Username) {
            return base.Channel.GetLogin(PostOffice, Username);
        }
        
        public System.Threading.Tasks.Task<long> GetLoginAsync(string PostOffice, string Username) {
            return base.Channel.GetLoginAsync(PostOffice, Username);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Login.GetLoginObjectPropertiesResponse Markum.Cloud.Libraries.Login.LoginSoap.GetLoginObjectProperties(Markum.Cloud.Libraries.Login.GetLoginObjectPropertiesRequest request) {
            return base.Channel.GetLoginObjectProperties(request);
        }
        
        public long GetLoginObjectProperties(string PostOffice, string Username, ref Markum.Cloud.Libraries.Login.Login ObjectProperties) {
            Markum.Cloud.Libraries.Login.GetLoginObjectPropertiesRequest inValue = new Markum.Cloud.Libraries.Login.GetLoginObjectPropertiesRequest();
            inValue.PostOffice = PostOffice;
            inValue.Username = Username;
            inValue.ObjectProperties = ObjectProperties;
            Markum.Cloud.Libraries.Login.GetLoginObjectPropertiesResponse retVal = ((Markum.Cloud.Libraries.Login.LoginSoap)(this)).GetLoginObjectProperties(inValue);
            ObjectProperties = retVal.ObjectProperties;
            return retVal.GetLoginObjectPropertiesResult;
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Login.GetLoginObjectPropertiesResponse> GetLoginObjectPropertiesAsync(Markum.Cloud.Libraries.Login.GetLoginObjectPropertiesRequest request) {
            return base.Channel.GetLoginObjectPropertiesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markum.Cloud.Libraries.Login.ListLoginResponse Markum.Cloud.Libraries.Login.LoginSoap.ListLogin(Markum.Cloud.Libraries.Login.ListLoginRequest request) {
            return base.Channel.ListLogin(request);
        }
        
        public long ListLogin(ref Markum.Cloud.Libraries.Login.Login[] ObjectList, string PostOffice, string Username, long Top, long MaxLength) {
            Markum.Cloud.Libraries.Login.ListLoginRequest inValue = new Markum.Cloud.Libraries.Login.ListLoginRequest();
            inValue.ObjectList = ObjectList;
            inValue.PostOffice = PostOffice;
            inValue.Username = Username;
            inValue.Top = Top;
            inValue.MaxLength = MaxLength;
            Markum.Cloud.Libraries.Login.ListLoginResponse retVal = ((Markum.Cloud.Libraries.Login.LoginSoap)(this)).ListLogin(inValue);
            ObjectList = retVal.ObjectList;
            return retVal.ListLoginResult;
        }
        
        public System.Threading.Tasks.Task<Markum.Cloud.Libraries.Login.ListLoginResponse> ListLoginAsync(Markum.Cloud.Libraries.Login.ListLoginRequest request) {
            return base.Channel.ListLoginAsync(request);
        }
        
        public long RemoveLogin(string PostOffice, string Username) {
            return base.Channel.RemoveLogin(PostOffice, Username);
        }
        
        public System.Threading.Tasks.Task<long> RemoveLoginAsync(string PostOffice, string Username) {
            return base.Channel.RemoveLoginAsync(PostOffice, Username);
        }
        
        public long EditLogin(string PostOffice, string Username, string NewPostOffice, string NewUsername, string NewPassword, long NewStatus, string NewDescription, string NewRights) {
            return base.Channel.EditLogin(PostOffice, Username, NewPostOffice, NewUsername, NewPassword, NewStatus, NewDescription, NewRights);
        }
        
        public System.Threading.Tasks.Task<long> EditLoginAsync(string PostOffice, string Username, string NewPostOffice, string NewUsername, string NewPassword, long NewStatus, string NewDescription, string NewRights) {
            return base.Channel.EditLoginAsync(PostOffice, Username, NewPostOffice, NewUsername, NewPassword, NewStatus, NewDescription, NewRights);
        }
    }
}
